/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/router/src/router_module';
import * as import8 from '@angular/material/core/compatibility/compatibility';
import * as import9 from '@angular/material/core/ripple/ripple';
import * as import10 from '@angular/material/core/option/option';
import * as import11 from '@angular/material/core/portal/portal-directives';
import * as import12 from '@angular/material/core/overlay/overlay-directives';
import * as import13 from '@angular/material/autocomplete/index';
import * as import14 from '@angular/material/button/button';
import * as import15 from '@angular/material/card/card';
import * as import16 from '@angular/material/chips/chip-list';
import * as import17 from '@angular/material/checkbox/checkbox';
import * as import18 from '@angular/material/core/line/line';
import * as import19 from '@angular/material/grid-list/grid-list';
import * as import20 from '@angular/material/core/platform/index';
import * as import21 from '@angular/material/input/index';
import * as import22 from '@angular/material/list/list';
import * as import23 from '@angular/material/progress-bar/progress-bar';
import * as import24 from '@angular/material/progress-spinner/progress-spinner';
import * as import25 from '@angular/material/select/index';
import * as import26 from '@angular/material/core/a11y/index';
import * as import27 from '@angular/material/sidenav/sidenav';
import * as import28 from '@angular/material/core/observe-content/observe-content';
import * as import29 from '@angular/material/tabs/tab-group';
import * as import30 from '@angular/material/toolbar/toolbar';
import * as import31 from '@angular/material/core/projection/projection';
import * as import32 from '@angular/material/core/rtl/dir';
import * as import33 from '@angular/material/button-toggle/button-toggle';
import * as import34 from '@angular/material/dialog/index';
import * as import35 from '@angular/http/src/http_module';
import * as import36 from '@angular/material/icon/icon';
import * as import37 from '@angular/material/menu/menu';
import * as import38 from '@angular/material/radio/radio';
import * as import39 from '@angular/material/slider/slider';
import * as import40 from '@angular/material/slide-toggle/slide-toggle';
import * as import41 from '@angular/material/snack-bar/index';
import * as import42 from '@angular/material/tooltip/tooltip';
import * as import43 from '@angular/material/core/style/index';
import * as import44 from '@angular/material/module';
import * as import45 from '@angular/common/src/localization';
import * as import46 from '@angular/core/src/application_init';
import * as import47 from '@angular/core/src/testability/testability';
import * as import48 from '@angular/core/src/application_ref';
import * as import49 from '@angular/core/src/linker/compiler';
import * as import50 from '@angular/material/core/gestures/gesture-config';
import * as import51 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import52 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import53 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import54 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import55 from '@angular/core/src/animation/animation_queue';
import * as import56 from '@angular/core/src/linker/view_utils';
import * as import57 from '@angular/platform-browser/src/browser/title';
import * as import58 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import59 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import60 from '@angular/material/core/overlay/overlay';
import * as import61 from '@angular/material/core/platform/platform';
import * as import62 from '@angular/material/core/a11y/interactivity-checker';
import * as import63 from '@angular/material/dialog/dialog';
import * as import64 from '@angular/http/src/backends/browser_xhr';
import * as import65 from '@angular/http/src/base_response_options';
import * as import66 from '@angular/http/src/backends/xhr_backend';
import * as import67 from '@angular/http/src/base_request_options';
import * as import68 from '@angular/material/snack-bar/snack-bar';
import * as import69 from '@angular/common/src/location/location';
import * as import70 from '@angular/router/src/url_tree';
import * as import71 from '@angular/router/src/router_outlet_map';
import * as import72 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import73 from '@angular/router/src/router_preloader';
import * as import74 from '../../../src/app/server.service';
import * as import75 from '../../../src/app/dialog.service';
import * as import76 from '@angular/core/src/di/injector';
import * as import77 from '../../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import78 from '../../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import79 from '../../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import80 from '../../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import81 from './patient-list.component.ngfactory';
import * as import82 from './patient.component.ngfactory';
import * as import83 from './patient-profile.component.ngfactory';
import * as import84 from './forms-list.component.ngfactory';
import * as import85 from './form.component.ngfactory';
import * as import86 from './page-not-found.component.ngfactory';
import * as import87 from './manage-protocol.component.ngfactory';
import * as import88 from './validate-protocol.component.ngfactory';
import * as import89 from './dialog.component.ngfactory';
import * as import90 from './app.component.ngfactory';
import * as import91 from '@angular/core/src/i18n/tokens';
import * as import92 from '@angular/core/src/application_tokens';
import * as import93 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import94 from '@angular/platform-browser/src/dom/events/key_events';
import * as import95 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import96 from '@angular/core/src/zone/ng_zone';
import * as import97 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import98 from '@angular/material/core/overlay/scroll/scroll-dispatcher';
import * as import99 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import100 from '@angular/material/core/overlay/overlay-container';
import * as import101 from '@angular/material/core/a11y/live-announcer';
import * as import102 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import103 from '@angular/material/icon/icon-registry';
import * as import104 from '@angular/material/core/style/focus-classes';
import * as import105 from '@angular/common/src/location/platform_location';
import * as import106 from '@angular/common/src/location/location_strategy';
import * as import107 from '../../../src/app/patient-list.component';
import * as import108 from '../../../src/app/patient.component';
import * as import109 from '../../../src/app/patient-profile.component';
import * as import110 from '../../../src/app/forms-list.component';
import * as import111 from '../../../src/app/form.component';
import * as import112 from '../../../src/app/page-not-found.component';
import * as import113 from '../../../src/app/manage-protocol.component';
import * as import114 from '../../../src/app/validate-protocol.component';
import * as import115 from '@angular/router/src/url_handling_strategy';
import * as import116 from '@angular/router/src/route_reuse_strategy';
import * as import117 from '@angular/router/src/router';
import * as import118 from '@angular/core/src/console';
import * as import119 from '@angular/core/src/error_handler';
import * as import120 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import121 from '@angular/platform-browser/src/dom/animation_driver';
import * as import122 from '@angular/core/src/render/api';
import * as import123 from '@angular/core/src/security';
import * as import124 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import125 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import126 from '@angular/http/src/interfaces';
import * as import127 from '@angular/http/src/http';
import * as import128 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import129 from '@angular/router/src/router_config_loader';
import * as import130 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ROUTER_FORROOT_GUARD_5:any;
  _RouterModule_6:import7.RouterModule;
  _CompatibilityModule_7:import8.CompatibilityModule;
  _MdRippleModule_8:import9.MdRippleModule;
  _MdOptionModule_9:import10.MdOptionModule;
  _PortalModule_10:import11.PortalModule;
  _OverlayModule_11:import12.OverlayModule;
  _MdAutocompleteModule_12:import13.MdAutocompleteModule;
  _MdButtonModule_13:import14.MdButtonModule;
  _MdCardModule_14:import15.MdCardModule;
  _MdChipsModule_15:import16.MdChipsModule;
  _MdCheckboxModule_16:import17.MdCheckboxModule;
  _MdLineModule_17:import18.MdLineModule;
  _MdGridListModule_18:import19.MdGridListModule;
  _PlatformModule_19:import20.PlatformModule;
  _MdInputModule_20:import21.MdInputModule;
  _MdListModule_21:import22.MdListModule;
  _MdProgressBarModule_22:import23.MdProgressBarModule;
  _MdProgressSpinnerModule_23:import24.MdProgressSpinnerModule;
  _MdSelectModule_24:import25.MdSelectModule;
  _A11yModule_25:import26.A11yModule;
  _MdSidenavModule_26:import27.MdSidenavModule;
  _ObserveContentModule_27:import28.ObserveContentModule;
  _MdTabsModule_28:import29.MdTabsModule;
  _MdToolbarModule_29:import30.MdToolbarModule;
  _ProjectionModule_30:import31.ProjectionModule;
  _RtlModule_31:import32.RtlModule;
  _MdButtonToggleModule_32:import33.MdButtonToggleModule;
  _MdDialogModule_33:import34.MdDialogModule;
  _HttpModule_34:import35.HttpModule;
  _MdIconModule_35:import36.MdIconModule;
  _MdMenuModule_36:import37.MdMenuModule;
  _MdRadioModule_37:import38.MdRadioModule;
  _MdSliderModule_38:import39.MdSliderModule;
  _MdSlideToggleModule_39:import40.MdSlideToggleModule;
  _MdSnackBarModule_40:import41.MdSnackBarModule;
  _MdTooltipModule_41:import42.MdTooltipModule;
  _StyleModule_42:import43.StyleModule;
  _MaterialRootModule_43:import44.MaterialRootModule;
  _AppModule_44:import1.AppModule;
  __LOCALE_ID_45:any;
  __NgLocalization_46:import45.NgLocaleLocalization;
  _ErrorHandler_47:any;
  _RouterInitializer_48:import7.RouterInitializer;
  _APP_INITIALIZER_49:any[];
  _ApplicationInitStatus_50:import46.ApplicationInitStatus;
  _Testability_51:import47.Testability;
  _ApplicationRef__52:import48.ApplicationRef_;
  __ApplicationRef_53:any;
  __Compiler_54:import49.Compiler;
  __APP_ID_55:any;
  __DOCUMENT_56:any;
  __HAMMER_GESTURE_CONFIG_57:import50.GestureConfig;
  __EVENT_MANAGER_PLUGINS_58:any[];
  __EventManager_59:import51.EventManager;
  _DomSharedStylesHost_60:import52.DomSharedStylesHost;
  __AnimationDriver_61:any;
  __DomRootRenderer_62:import53.DomRootRenderer_;
  __NgProbeToken_63:any[];
  __RootRenderer_64:any;
  __DomSanitizer_65:import54.DomSanitizerImpl;
  __Sanitizer_66:any;
  __AnimationQueue_67:import55.AnimationQueue;
  __ViewUtils_68:import56.ViewUtils;
  __IterableDiffers_69:any;
  __KeyValueDiffers_70:any;
  __SharedStylesHost_71:any;
  __Title_72:import57.Title;
  __RadioControlRegistry_73:import58.RadioControlRegistry;
  __ScrollDispatcher_74:any;
  __ViewportRuler_75:any;
  __OverlayContainer_76:any;
  __OverlayPositionBuilder_77:import59.OverlayPositionBuilder;
  __Overlay_78:import60.Overlay;
  __Platform_79:import61.Platform;
  __InteractivityChecker_80:import62.InteractivityChecker;
  __LiveAnnouncer_81:any;
  __DomProjection_82:import31.DomProjection;
  __UniqueSelectionDispatcher_83:any;
  __MdDialog_84:import63.MdDialog;
  __BrowserXhr_85:import64.BrowserXhr;
  __ResponseOptions_86:import65.BaseResponseOptions;
  __XSRFStrategy_87:any;
  __XHRBackend_88:import66.XHRBackend;
  __RequestOptions_89:import67.BaseRequestOptions;
  __Http_90:any;
  __MdIconRegistry_91:any;
  __MdSnackBar_92:import68.MdSnackBar;
  __FocusOriginMonitor_93:any;
  __ROUTER_CONFIGURATION_94:any;
  __LocationStrategy_95:any;
  __Location_96:import69.Location;
  __UrlSerializer_97:import70.DefaultUrlSerializer;
  __RouterOutletMap_98:import71.RouterOutletMap;
  __NgModuleFactoryLoader_99:import72.SystemJsNgModuleLoader;
  __ROUTES_100:any[];
  __Router_101:any;
  __ActivatedRoute_102:any;
  _NoPreloading_103:import73.NoPreloading;
  _PreloadingStrategy_104:any;
  _RouterPreloader_105:import73.RouterPreloader;
  __PreloadAllModules_106:import73.PreloadAllModules;
  __ROUTER_INITIALIZER_107:any;
  __APP_BOOTSTRAP_LISTENER_108:any[];
  __Server_109:import74.Server;
  __DialogService_110:import75.DialogService;
  constructor(parent:import76.Injector) {
    super(parent,[
      import77.MdDialogContainerNgFactory,
      import78.MdSnackBarContainerNgFactory,
      import79.SimpleSnackBarNgFactory,
      import80.TooltipComponentNgFactory,
      import81.PatientListComponentNgFactory,
      import82.PatientComponentNgFactory,
      import83.PatientProfileComponentNgFactory,
      import84.FormsListComponentNgFactory,
      import85.FormComponentNgFactory,
      import86.PageNotFoundComponentNgFactory,
      import87.ManageProtocolComponentNgFactory,
      import88.ValidateProtocolComponentNgFactory,
      import89.DialogComponentNgFactory,
      import90.AppComponentNgFactory
    ]
    ,[import90.AppComponentNgFactory]);
  }
  get _LOCALE_ID_45():any {
    if ((this.__LOCALE_ID_45 == null)) { (this.__LOCALE_ID_45 = import3._localeFactory(this.parent.get(import91.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_45;
  }
  get _NgLocalization_46():import45.NgLocaleLocalization {
    if ((this.__NgLocalization_46 == null)) { (this.__NgLocalization_46 = new import45.NgLocaleLocalization(this._LOCALE_ID_45)); }
    return this.__NgLocalization_46;
  }
  get _ApplicationRef_53():any {
    if ((this.__ApplicationRef_53 == null)) { (this.__ApplicationRef_53 = this._ApplicationRef__52); }
    return this.__ApplicationRef_53;
  }
  get _Compiler_54():import49.Compiler {
    if ((this.__Compiler_54 == null)) { (this.__Compiler_54 = new import49.Compiler()); }
    return this.__Compiler_54;
  }
  get _APP_ID_55():any {
    if ((this.__APP_ID_55 == null)) { (this.__APP_ID_55 = import92._appIdRandomProviderFactory()); }
    return this.__APP_ID_55;
  }
  get _DOCUMENT_56():any {
    if ((this.__DOCUMENT_56 == null)) { (this.__DOCUMENT_56 = import4._document()); }
    return this.__DOCUMENT_56;
  }
  get _HAMMER_GESTURE_CONFIG_57():import50.GestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_57 == null)) { (this.__HAMMER_GESTURE_CONFIG_57 = new import50.GestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_57;
  }
  get _EVENT_MANAGER_PLUGINS_58():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_58 == null)) { (this.__EVENT_MANAGER_PLUGINS_58 = [
      new import93.DomEventsPlugin(),
      new import94.KeyEventsPlugin(),
      new import95.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_57)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_58;
  }
  get _EventManager_59():import51.EventManager {
    if ((this.__EventManager_59 == null)) { (this.__EventManager_59 = new import51.EventManager(this._EVENT_MANAGER_PLUGINS_58,this.parent.get(import96.NgZone))); }
    return this.__EventManager_59;
  }
  get _AnimationDriver_61():any {
    if ((this.__AnimationDriver_61 == null)) { (this.__AnimationDriver_61 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_61;
  }
  get _DomRootRenderer_62():import53.DomRootRenderer_ {
    if ((this.__DomRootRenderer_62 == null)) { (this.__DomRootRenderer_62 = new import53.DomRootRenderer_(this._DOCUMENT_56,this._EventManager_59,this._DomSharedStylesHost_60,this._AnimationDriver_61,this._APP_ID_55)); }
    return this.__DomRootRenderer_62;
  }
  get _NgProbeToken_63():any[] {
    if ((this.__NgProbeToken_63 == null)) { (this.__NgProbeToken_63 = [import7.routerNgProbeToken()]); }
    return this.__NgProbeToken_63;
  }
  get _RootRenderer_64():any {
    if ((this.__RootRenderer_64 == null)) { (this.__RootRenderer_64 = import97._createConditionalRootRenderer(this._DomRootRenderer_62,this.parent.get(import97.NgProbeToken,(null as any)),this._NgProbeToken_63)); }
    return this.__RootRenderer_64;
  }
  get _DomSanitizer_65():import54.DomSanitizerImpl {
    if ((this.__DomSanitizer_65 == null)) { (this.__DomSanitizer_65 = new import54.DomSanitizerImpl()); }
    return this.__DomSanitizer_65;
  }
  get _Sanitizer_66():any {
    if ((this.__Sanitizer_66 == null)) { (this.__Sanitizer_66 = this._DomSanitizer_65); }
    return this.__Sanitizer_66;
  }
  get _AnimationQueue_67():import55.AnimationQueue {
    if ((this.__AnimationQueue_67 == null)) { (this.__AnimationQueue_67 = new import55.AnimationQueue(this.parent.get(import96.NgZone))); }
    return this.__AnimationQueue_67;
  }
  get _ViewUtils_68():import56.ViewUtils {
    if ((this.__ViewUtils_68 == null)) { (this.__ViewUtils_68 = new import56.ViewUtils(this._RootRenderer_64,this._Sanitizer_66,this._AnimationQueue_67)); }
    return this.__ViewUtils_68;
  }
  get _IterableDiffers_69():any {
    if ((this.__IterableDiffers_69 == null)) { (this.__IterableDiffers_69 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_69;
  }
  get _KeyValueDiffers_70():any {
    if ((this.__KeyValueDiffers_70 == null)) { (this.__KeyValueDiffers_70 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_70;
  }
  get _SharedStylesHost_71():any {
    if ((this.__SharedStylesHost_71 == null)) { (this.__SharedStylesHost_71 = this._DomSharedStylesHost_60); }
    return this.__SharedStylesHost_71;
  }
  get _Title_72():import57.Title {
    if ((this.__Title_72 == null)) { (this.__Title_72 = new import57.Title()); }
    return this.__Title_72;
  }
  get _RadioControlRegistry_73():import58.RadioControlRegistry {
    if ((this.__RadioControlRegistry_73 == null)) { (this.__RadioControlRegistry_73 = new import58.RadioControlRegistry()); }
    return this.__RadioControlRegistry_73;
  }
  get _ScrollDispatcher_74():any {
    if ((this.__ScrollDispatcher_74 == null)) { (this.__ScrollDispatcher_74 = import98.SCROLL_DISPATCHER_PROVIDER_FACTORY(this.parent.get(import98.ScrollDispatcher,(null as any)))); }
    return this.__ScrollDispatcher_74;
  }
  get _ViewportRuler_75():any {
    if ((this.__ViewportRuler_75 == null)) { (this.__ViewportRuler_75 = import99.VIEWPORT_RULER_PROVIDER_FACTORY(this.parent.get(import99.ViewportRuler,(null as any)),this._ScrollDispatcher_74)); }
    return this.__ViewportRuler_75;
  }
  get _OverlayContainer_76():any {
    if ((this.__OverlayContainer_76 == null)) { (this.__OverlayContainer_76 = import100.OVERLAY_CONTAINER_PROVIDER_FACTORY(this.parent.get(import100.OverlayContainer,(null as any)))); }
    return this.__OverlayContainer_76;
  }
  get _OverlayPositionBuilder_77():import59.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_77 == null)) { (this.__OverlayPositionBuilder_77 = new import59.OverlayPositionBuilder(this._ViewportRuler_75)); }
    return this.__OverlayPositionBuilder_77;
  }
  get _Overlay_78():import60.Overlay {
    if ((this.__Overlay_78 == null)) { (this.__Overlay_78 = new import60.Overlay(this._OverlayContainer_76,this,this._OverlayPositionBuilder_77,this._ApplicationRef_53,this,this.parent.get(import96.NgZone))); }
    return this.__Overlay_78;
  }
  get _Platform_79():import61.Platform {
    if ((this.__Platform_79 == null)) { (this.__Platform_79 = new import61.Platform()); }
    return this.__Platform_79;
  }
  get _InteractivityChecker_80():import62.InteractivityChecker {
    if ((this.__InteractivityChecker_80 == null)) { (this.__InteractivityChecker_80 = new import62.InteractivityChecker(this._Platform_79)); }
    return this.__InteractivityChecker_80;
  }
  get _LiveAnnouncer_81():any {
    if ((this.__LiveAnnouncer_81 == null)) { (this.__LiveAnnouncer_81 = import101.LIVE_ANNOUNCER_PROVIDER_FACTORY(this.parent.get(import101.LiveAnnouncer,(null as any)),this.parent.get(import101.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__LiveAnnouncer_81;
  }
  get _DomProjection_82():import31.DomProjection {
    if ((this.__DomProjection_82 == null)) { (this.__DomProjection_82 = new import31.DomProjection()); }
    return this.__DomProjection_82;
  }
  get _UniqueSelectionDispatcher_83():any {
    if ((this.__UniqueSelectionDispatcher_83 == null)) { (this.__UniqueSelectionDispatcher_83 = import102.UNIQUE_SELECTION_DISPATCHER_PROVIDER_FACTORY(this.parent.get(import102.UniqueSelectionDispatcher,(null as any)))); }
    return this.__UniqueSelectionDispatcher_83;
  }
  get _MdDialog_84():import63.MdDialog {
    if ((this.__MdDialog_84 == null)) { (this.__MdDialog_84 = new import63.MdDialog(this._Overlay_78,this,this.parent.get(import63.MdDialog,(null as any)))); }
    return this.__MdDialog_84;
  }
  get _BrowserXhr_85():import64.BrowserXhr {
    if ((this.__BrowserXhr_85 == null)) { (this.__BrowserXhr_85 = new import64.BrowserXhr()); }
    return this.__BrowserXhr_85;
  }
  get _ResponseOptions_86():import65.BaseResponseOptions {
    if ((this.__ResponseOptions_86 == null)) { (this.__ResponseOptions_86 = new import65.BaseResponseOptions()); }
    return this.__ResponseOptions_86;
  }
  get _XSRFStrategy_87():any {
    if ((this.__XSRFStrategy_87 == null)) { (this.__XSRFStrategy_87 = import35._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_87;
  }
  get _XHRBackend_88():import66.XHRBackend {
    if ((this.__XHRBackend_88 == null)) { (this.__XHRBackend_88 = new import66.XHRBackend(this._BrowserXhr_85,this._ResponseOptions_86,this._XSRFStrategy_87)); }
    return this.__XHRBackend_88;
  }
  get _RequestOptions_89():import67.BaseRequestOptions {
    if ((this.__RequestOptions_89 == null)) { (this.__RequestOptions_89 = new import67.BaseRequestOptions()); }
    return this.__RequestOptions_89;
  }
  get _Http_90():any {
    if ((this.__Http_90 == null)) { (this.__Http_90 = import35.httpFactory(this._XHRBackend_88,this._RequestOptions_89)); }
    return this.__Http_90;
  }
  get _MdIconRegistry_91():any {
    if ((this.__MdIconRegistry_91 == null)) { (this.__MdIconRegistry_91 = import36.ICON_REGISTRY_PROVIDER_FACTORY(this.parent.get(import103.MdIconRegistry,(null as any)),this._Http_90,this._DomSanitizer_65)); }
    return this.__MdIconRegistry_91;
  }
  get _MdSnackBar_92():import68.MdSnackBar {
    if ((this.__MdSnackBar_92 == null)) { (this.__MdSnackBar_92 = new import68.MdSnackBar(this._Overlay_78,this._LiveAnnouncer_81,this.parent.get(import68.MdSnackBar,(null as any)))); }
    return this.__MdSnackBar_92;
  }
  get _FocusOriginMonitor_93():any {
    if ((this.__FocusOriginMonitor_93 == null)) { (this.__FocusOriginMonitor_93 = import104.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY(this.parent.get(import104.FocusOriginMonitor,(null as any)))); }
    return this.__FocusOriginMonitor_93;
  }
  get _ROUTER_CONFIGURATION_94():any {
    if ((this.__ROUTER_CONFIGURATION_94 == null)) { (this.__ROUTER_CONFIGURATION_94 = {}); }
    return this.__ROUTER_CONFIGURATION_94;
  }
  get _LocationStrategy_95():any {
    if ((this.__LocationStrategy_95 == null)) { (this.__LocationStrategy_95 = import7.provideLocationStrategy(this.parent.get(import105.PlatformLocation),this.parent.get(import106.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_94)); }
    return this.__LocationStrategy_95;
  }
  get _Location_96():import69.Location {
    if ((this.__Location_96 == null)) { (this.__Location_96 = new import69.Location(this._LocationStrategy_95)); }
    return this.__Location_96;
  }
  get _UrlSerializer_97():import70.DefaultUrlSerializer {
    if ((this.__UrlSerializer_97 == null)) { (this.__UrlSerializer_97 = new import70.DefaultUrlSerializer()); }
    return this.__UrlSerializer_97;
  }
  get _RouterOutletMap_98():import71.RouterOutletMap {
    if ((this.__RouterOutletMap_98 == null)) { (this.__RouterOutletMap_98 = new import71.RouterOutletMap()); }
    return this.__RouterOutletMap_98;
  }
  get _NgModuleFactoryLoader_99():import72.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_99 == null)) { (this.__NgModuleFactoryLoader_99 = new import72.SystemJsNgModuleLoader(this._Compiler_54,this.parent.get(import72.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_99;
  }
  get _ROUTES_100():any[] {
      if ((this.__ROUTES_100 == null)) { (this.__ROUTES_100 = [[
        {
          path: '',
          pathMatch: 'full',
          redirectTo: '/patient-list'
        }
        ,
        {
          path: 'patient-list',
          component: import107.PatientListComponent
        }
        ,
        {
          path: 'patient',
          component: import108.PatientComponent,
          children: [
            {
              path: '',
              pathMatch: 'full',
              redirectTo: '0/profile'
            }
            ,
            {
              path: ':id',
              pathMatch: 'full',
              redirectTo: ':id/profile'
            }
            ,
            {
              path: ':id/profile',
              component: import109.PatientProfileComponent
            }
            ,
            {
              path: ':id/forms-list',
              component: import110.FormsListComponent
            }
            ,
            {
              path: ':id/form/:type',
              component: import111.FormComponent
            }
            ,
            {
              path: '**',
              component: import112.PageNotFoundComponent
            }

          ]

        }
        ,
        {
          path: 'manage-protocol',
          component: import113.ManageProtocolComponent
        }
        ,
        {
          path: 'validate-protocol',
          component: import114.ValidateProtocolComponent
        }
        ,
        {
          path: '**',
          component: import112.PageNotFoundComponent
        }

      ]
    ]); }
    return this.__ROUTES_100;
  }
  get _Router_101():any {
    if ((this.__Router_101 == null)) { (this.__Router_101 = import7.setupRouter(this._ApplicationRef_53,this._UrlSerializer_97,this._RouterOutletMap_98,this._Location_96,this,this._NgModuleFactoryLoader_99,this._Compiler_54,this._ROUTES_100,this._ROUTER_CONFIGURATION_94,this.parent.get(import115.UrlHandlingStrategy,(null as any)),this.parent.get(import116.RouteReuseStrategy,(null as any)))); }
    return this.__Router_101;
  }
  get _ActivatedRoute_102():any {
    if ((this.__ActivatedRoute_102 == null)) { (this.__ActivatedRoute_102 = import7.rootRoute(this._Router_101)); }
    return this.__ActivatedRoute_102;
  }
  get _PreloadAllModules_106():import73.PreloadAllModules {
    if ((this.__PreloadAllModules_106 == null)) { (this.__PreloadAllModules_106 = new import73.PreloadAllModules()); }
    return this.__PreloadAllModules_106;
  }
  get _ROUTER_INITIALIZER_107():any {
    if ((this.__ROUTER_INITIALIZER_107 == null)) { (this.__ROUTER_INITIALIZER_107 = import7.getBootstrapListener(this._RouterInitializer_48)); }
    return this.__ROUTER_INITIALIZER_107;
  }
  get _APP_BOOTSTRAP_LISTENER_108():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_108 == null)) { (this.__APP_BOOTSTRAP_LISTENER_108 = [this._ROUTER_INITIALIZER_107]); }
    return this.__APP_BOOTSTRAP_LISTENER_108;
  }
  get _Server_109():import74.Server {
    if ((this.__Server_109 == null)) { (this.__Server_109 = new import74.Server(this._Http_90)); }
    return this.__Server_109;
  }
  get _DialogService_110():import75.DialogService {
    if ((this.__DialogService_110 == null)) { (this.__DialogService_110 = new import75.DialogService(this._MdDialog_84)); }
    return this.__DialogService_110;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ROUTER_FORROOT_GUARD_5 = import7.provideForRootGuard(this.parent.get(import117.Router,(null as any)));
    this._RouterModule_6 = new import7.RouterModule(this._ROUTER_FORROOT_GUARD_5);
    this._CompatibilityModule_7 = new import8.CompatibilityModule();
    this._MdRippleModule_8 = new import9.MdRippleModule();
    this._MdOptionModule_9 = new import10.MdOptionModule();
    this._PortalModule_10 = new import11.PortalModule();
    this._OverlayModule_11 = new import12.OverlayModule();
    this._MdAutocompleteModule_12 = new import13.MdAutocompleteModule();
    this._MdButtonModule_13 = new import14.MdButtonModule();
    this._MdCardModule_14 = new import15.MdCardModule();
    this._MdChipsModule_15 = new import16.MdChipsModule();
    this._MdCheckboxModule_16 = new import17.MdCheckboxModule();
    this._MdLineModule_17 = new import18.MdLineModule();
    this._MdGridListModule_18 = new import19.MdGridListModule();
    this._PlatformModule_19 = new import20.PlatformModule();
    this._MdInputModule_20 = new import21.MdInputModule();
    this._MdListModule_21 = new import22.MdListModule();
    this._MdProgressBarModule_22 = new import23.MdProgressBarModule();
    this._MdProgressSpinnerModule_23 = new import24.MdProgressSpinnerModule();
    this._MdSelectModule_24 = new import25.MdSelectModule();
    this._A11yModule_25 = new import26.A11yModule();
    this._MdSidenavModule_26 = new import27.MdSidenavModule();
    this._ObserveContentModule_27 = new import28.ObserveContentModule();
    this._MdTabsModule_28 = new import29.MdTabsModule();
    this._MdToolbarModule_29 = new import30.MdToolbarModule();
    this._ProjectionModule_30 = new import31.ProjectionModule();
    this._RtlModule_31 = new import32.RtlModule();
    this._MdButtonToggleModule_32 = new import33.MdButtonToggleModule();
    this._MdDialogModule_33 = new import34.MdDialogModule();
    this._HttpModule_34 = new import35.HttpModule();
    this._MdIconModule_35 = new import36.MdIconModule();
    this._MdMenuModule_36 = new import37.MdMenuModule();
    this._MdRadioModule_37 = new import38.MdRadioModule();
    this._MdSliderModule_38 = new import39.MdSliderModule();
    this._MdSlideToggleModule_39 = new import40.MdSlideToggleModule();
    this._MdSnackBarModule_40 = new import41.MdSnackBarModule();
    this._MdTooltipModule_41 = new import42.MdTooltipModule();
    this._StyleModule_42 = new import43.StyleModule();
    this._MaterialRootModule_43 = new import44.MaterialRootModule();
    this._AppModule_44 = new import1.AppModule();
    this._ErrorHandler_47 = import4.errorHandler();
    this._RouterInitializer_48 = new import7.RouterInitializer(this);
    this._APP_INITIALIZER_49 = [import7.getAppInitializer(this._RouterInitializer_48)];
    this._ApplicationInitStatus_50 = new import46.ApplicationInitStatus(this._APP_INITIALIZER_49);
    this._Testability_51 = new import47.Testability(this.parent.get(import96.NgZone));
    this._ApplicationRef__52 = new import48.ApplicationRef_(this.parent.get(import96.NgZone),this.parent.get(import118.Console),this,this._ErrorHandler_47,this,this._ApplicationInitStatus_50,this.parent.get(import47.TestabilityRegistry,(null as any)),this._Testability_51);
    this._DomSharedStylesHost_60 = new import52.DomSharedStylesHost(this._DOCUMENT_56);
    this._NoPreloading_103 = new import73.NoPreloading();
    this._PreloadingStrategy_104 = this._NoPreloading_103;
    this._RouterPreloader_105 = new import73.RouterPreloader(this._Router_101,this._NgModuleFactoryLoader_99,this._Compiler_54,this,this._PreloadingStrategy_104);
    return this._AppModule_44;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_5; }
    if ((token === import7.RouterModule)) { return this._RouterModule_6; }
    if ((token === import8.CompatibilityModule)) { return this._CompatibilityModule_7; }
    if ((token === import9.MdRippleModule)) { return this._MdRippleModule_8; }
    if ((token === import10.MdOptionModule)) { return this._MdOptionModule_9; }
    if ((token === import11.PortalModule)) { return this._PortalModule_10; }
    if ((token === import12.OverlayModule)) { return this._OverlayModule_11; }
    if ((token === import13.MdAutocompleteModule)) { return this._MdAutocompleteModule_12; }
    if ((token === import14.MdButtonModule)) { return this._MdButtonModule_13; }
    if ((token === import15.MdCardModule)) { return this._MdCardModule_14; }
    if ((token === import16.MdChipsModule)) { return this._MdChipsModule_15; }
    if ((token === import17.MdCheckboxModule)) { return this._MdCheckboxModule_16; }
    if ((token === import18.MdLineModule)) { return this._MdLineModule_17; }
    if ((token === import19.MdGridListModule)) { return this._MdGridListModule_18; }
    if ((token === import20.PlatformModule)) { return this._PlatformModule_19; }
    if ((token === import21.MdInputModule)) { return this._MdInputModule_20; }
    if ((token === import22.MdListModule)) { return this._MdListModule_21; }
    if ((token === import23.MdProgressBarModule)) { return this._MdProgressBarModule_22; }
    if ((token === import24.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_23; }
    if ((token === import25.MdSelectModule)) { return this._MdSelectModule_24; }
    if ((token === import26.A11yModule)) { return this._A11yModule_25; }
    if ((token === import27.MdSidenavModule)) { return this._MdSidenavModule_26; }
    if ((token === import28.ObserveContentModule)) { return this._ObserveContentModule_27; }
    if ((token === import29.MdTabsModule)) { return this._MdTabsModule_28; }
    if ((token === import30.MdToolbarModule)) { return this._MdToolbarModule_29; }
    if ((token === import31.ProjectionModule)) { return this._ProjectionModule_30; }
    if ((token === import32.RtlModule)) { return this._RtlModule_31; }
    if ((token === import33.MdButtonToggleModule)) { return this._MdButtonToggleModule_32; }
    if ((token === import34.MdDialogModule)) { return this._MdDialogModule_33; }
    if ((token === import35.HttpModule)) { return this._HttpModule_34; }
    if ((token === import36.MdIconModule)) { return this._MdIconModule_35; }
    if ((token === import37.MdMenuModule)) { return this._MdMenuModule_36; }
    if ((token === import38.MdRadioModule)) { return this._MdRadioModule_37; }
    if ((token === import39.MdSliderModule)) { return this._MdSliderModule_38; }
    if ((token === import40.MdSlideToggleModule)) { return this._MdSlideToggleModule_39; }
    if ((token === import41.MdSnackBarModule)) { return this._MdSnackBarModule_40; }
    if ((token === import42.MdTooltipModule)) { return this._MdTooltipModule_41; }
    if ((token === import43.StyleModule)) { return this._StyleModule_42; }
    if ((token === import44.MaterialRootModule)) { return this._MaterialRootModule_43; }
    if ((token === import1.AppModule)) { return this._AppModule_44; }
    if ((token === import91.LOCALE_ID)) { return this._LOCALE_ID_45; }
    if ((token === import45.NgLocalization)) { return this._NgLocalization_46; }
    if ((token === import119.ErrorHandler)) { return this._ErrorHandler_47; }
    if ((token === import7.RouterInitializer)) { return this._RouterInitializer_48; }
    if ((token === import46.APP_INITIALIZER)) { return this._APP_INITIALIZER_49; }
    if ((token === import46.ApplicationInitStatus)) { return this._ApplicationInitStatus_50; }
    if ((token === import47.Testability)) { return this._Testability_51; }
    if ((token === import48.ApplicationRef_)) { return this._ApplicationRef__52; }
    if ((token === import48.ApplicationRef)) { return this._ApplicationRef_53; }
    if ((token === import49.Compiler)) { return this._Compiler_54; }
    if ((token === import92.APP_ID)) { return this._APP_ID_55; }
    if ((token === import120.DOCUMENT)) { return this._DOCUMENT_56; }
    if ((token === import95.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_57; }
    if ((token === import51.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_58; }
    if ((token === import51.EventManager)) { return this._EventManager_59; }
    if ((token === import52.DomSharedStylesHost)) { return this._DomSharedStylesHost_60; }
    if ((token === import121.AnimationDriver)) { return this._AnimationDriver_61; }
    if ((token === import53.DomRootRenderer)) { return this._DomRootRenderer_62; }
    if ((token === import48.NgProbeToken)) { return this._NgProbeToken_63; }
    if ((token === import122.RootRenderer)) { return this._RootRenderer_64; }
    if ((token === import54.DomSanitizer)) { return this._DomSanitizer_65; }
    if ((token === import123.Sanitizer)) { return this._Sanitizer_66; }
    if ((token === import55.AnimationQueue)) { return this._AnimationQueue_67; }
    if ((token === import56.ViewUtils)) { return this._ViewUtils_68; }
    if ((token === import124.IterableDiffers)) { return this._IterableDiffers_69; }
    if ((token === import125.KeyValueDiffers)) { return this._KeyValueDiffers_70; }
    if ((token === import52.SharedStylesHost)) { return this._SharedStylesHost_71; }
    if ((token === import57.Title)) { return this._Title_72; }
    if ((token === import58.RadioControlRegistry)) { return this._RadioControlRegistry_73; }
    if ((token === import98.ScrollDispatcher)) { return this._ScrollDispatcher_74; }
    if ((token === import99.ViewportRuler)) { return this._ViewportRuler_75; }
    if ((token === import100.OverlayContainer)) { return this._OverlayContainer_76; }
    if ((token === import59.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_77; }
    if ((token === import60.Overlay)) { return this._Overlay_78; }
    if ((token === import61.Platform)) { return this._Platform_79; }
    if ((token === import62.InteractivityChecker)) { return this._InteractivityChecker_80; }
    if ((token === import101.LiveAnnouncer)) { return this._LiveAnnouncer_81; }
    if ((token === import31.DomProjection)) { return this._DomProjection_82; }
    if ((token === import102.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_83; }
    if ((token === import63.MdDialog)) { return this._MdDialog_84; }
    if ((token === import64.BrowserXhr)) { return this._BrowserXhr_85; }
    if ((token === import65.ResponseOptions)) { return this._ResponseOptions_86; }
    if ((token === import126.XSRFStrategy)) { return this._XSRFStrategy_87; }
    if ((token === import66.XHRBackend)) { return this._XHRBackend_88; }
    if ((token === import67.RequestOptions)) { return this._RequestOptions_89; }
    if ((token === import127.Http)) { return this._Http_90; }
    if ((token === import103.MdIconRegistry)) { return this._MdIconRegistry_91; }
    if ((token === import68.MdSnackBar)) { return this._MdSnackBar_92; }
    if ((token === import104.FocusOriginMonitor)) { return this._FocusOriginMonitor_93; }
    if ((token === import7.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_94; }
    if ((token === import106.LocationStrategy)) { return this._LocationStrategy_95; }
    if ((token === import69.Location)) { return this._Location_96; }
    if ((token === import70.UrlSerializer)) { return this._UrlSerializer_97; }
    if ((token === import71.RouterOutletMap)) { return this._RouterOutletMap_98; }
    if ((token === import128.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_99; }
    if ((token === import129.ROUTES)) { return this._ROUTES_100; }
    if ((token === import117.Router)) { return this._Router_101; }
    if ((token === import130.ActivatedRoute)) { return this._ActivatedRoute_102; }
    if ((token === import73.NoPreloading)) { return this._NoPreloading_103; }
    if ((token === import73.PreloadingStrategy)) { return this._PreloadingStrategy_104; }
    if ((token === import73.RouterPreloader)) { return this._RouterPreloader_105; }
    if ((token === import73.PreloadAllModules)) { return this._PreloadAllModules_106; }
    if ((token === import7.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_107; }
    if ((token === import92.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_108; }
    if ((token === import74.Server)) { return this._Server_109; }
    if ((token === import75.DialogService)) { return this._DialogService_110; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__52.ngOnDestroy();
    this._DomSharedStylesHost_60.ngOnDestroy();
    this._RouterPreloader_105.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);