/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/router/src/router_module';
import * as import8 from '@angular/material/core/compatibility/compatibility';
import * as import9 from '@angular/material/core/ripple/ripple';
import * as import10 from '@angular/material/core/option/option';
import * as import11 from '@angular/material/core/portal/portal-directives';
import * as import12 from '@angular/material/core/overlay/overlay-directives';
import * as import13 from '@angular/material/autocomplete/index';
import * as import14 from '@angular/material/button/button';
import * as import15 from '@angular/material/card/card';
import * as import16 from '@angular/material/chips/chip-list';
import * as import17 from '@angular/material/checkbox/checkbox';
import * as import18 from '@angular/material/core/line/line';
import * as import19 from '@angular/material/grid-list/grid-list';
import * as import20 from '@angular/material/core/platform/index';
import * as import21 from '@angular/material/input/index';
import * as import22 from '@angular/material/list/list';
import * as import23 from '@angular/material/progress-bar/progress-bar';
import * as import24 from '@angular/material/progress-spinner/progress-spinner';
import * as import25 from '@angular/material/select/index';
import * as import26 from '@angular/material/core/a11y/index';
import * as import27 from '@angular/material/sidenav/sidenav';
import * as import28 from '@angular/material/core/observe-content/observe-content';
import * as import29 from '@angular/material/tabs/tab-group';
import * as import30 from '@angular/material/toolbar/toolbar';
import * as import31 from '@angular/material/core/projection/projection';
import * as import32 from '@angular/material/core/rtl/dir';
import * as import33 from '@angular/material/button-toggle/button-toggle';
import * as import34 from '@angular/material/dialog/index';
import * as import35 from '@angular/http/src/http_module';
import * as import36 from '@angular/material/icon/icon';
import * as import37 from '@angular/material/menu/menu';
import * as import38 from '@angular/material/radio/radio';
import * as import39 from '@angular/material/slider/slider';
import * as import40 from '@angular/material/slide-toggle/slide-toggle';
import * as import41 from '@angular/material/snack-bar/index';
import * as import42 from '@angular/material/tooltip/tooltip';
import * as import43 from '@angular/material/core/style/index';
import * as import44 from '@angular/material/module';
import * as import45 from '@angular/common/src/localization';
import * as import46 from '@angular/core/src/application_init';
import * as import47 from '@angular/core/src/testability/testability';
import * as import48 from '@angular/core/src/application_ref';
import * as import49 from '@angular/core/src/linker/compiler';
import * as import50 from '@angular/material/core/gestures/gesture-config';
import * as import51 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import52 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import53 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import54 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import55 from '@angular/core/src/animation/animation_queue';
import * as import56 from '@angular/core/src/linker/view_utils';
import * as import57 from '@angular/platform-browser/src/browser/title';
import * as import58 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import59 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import60 from '@angular/material/core/overlay/overlay';
import * as import61 from '@angular/material/core/platform/platform';
import * as import62 from '@angular/material/core/a11y/interactivity-checker';
import * as import63 from '@angular/material/dialog/dialog';
import * as import64 from '@angular/http/src/backends/browser_xhr';
import * as import65 from '@angular/http/src/base_response_options';
import * as import66 from '@angular/http/src/backends/xhr_backend';
import * as import67 from '@angular/http/src/base_request_options';
import * as import68 from '@angular/material/snack-bar/snack-bar';
import * as import69 from '@angular/common/src/location/location';
import * as import70 from '@angular/router/src/url_tree';
import * as import71 from '@angular/router/src/router_outlet_map';
import * as import72 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import73 from '@angular/router/src/router_preloader';
import * as import74 from '../../../src/app/server.service';
import * as import75 from '../../../src/app/dialog.service';
import * as import76 from '../../../src/app/auth.service';
import * as import77 from '../../../src/app/auth-guard.service';
import * as import78 from '@angular/core/src/di/injector';
import * as import79 from '../../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import80 from '../../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import81 from '../../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import82 from '../../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import83 from './patient-list.component.ngfactory';
import * as import84 from './patient.component.ngfactory';
import * as import85 from './patient-profile.component.ngfactory';
import * as import86 from './forms-list.component.ngfactory';
import * as import87 from './form.component.ngfactory';
import * as import88 from './page-not-found.component.ngfactory';
import * as import89 from './manage-protocol.component.ngfactory';
import * as import90 from './validate-protocol.component.ngfactory';
import * as import91 from './dialog.component.ngfactory';
import * as import92 from './app.component.ngfactory';
import * as import93 from '@angular/core/src/i18n/tokens';
import * as import94 from '@angular/core/src/application_tokens';
import * as import95 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import96 from '@angular/platform-browser/src/dom/events/key_events';
import * as import97 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import98 from '@angular/core/src/zone/ng_zone';
import * as import99 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import100 from '@angular/material/core/overlay/scroll/scroll-dispatcher';
import * as import101 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import102 from '@angular/material/core/overlay/overlay-container';
import * as import103 from '@angular/material/core/a11y/live-announcer';
import * as import104 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import105 from '@angular/material/icon/icon-registry';
import * as import106 from '@angular/material/core/style/focus-classes';
import * as import107 from '@angular/common/src/location/platform_location';
import * as import108 from '@angular/common/src/location/location_strategy';
import * as import109 from '../../../src/app/patient-list.component';
import * as import110 from '../../../src/app/patient.component';
import * as import111 from '../../../src/app/patient-profile.component';
import * as import112 from '../../../src/app/forms-list.component';
import * as import113 from '../../../src/app/form.component';
import * as import114 from '../../../src/app/page-not-found.component';
import * as import115 from '../../../src/app/manage-protocol.component';
import * as import116 from '../../../src/app/validate-protocol.component';
import * as import117 from '@angular/router/src/url_handling_strategy';
import * as import118 from '@angular/router/src/route_reuse_strategy';
import * as import119 from '@angular/router/src/router';
import * as import120 from '@angular/core/src/console';
import * as import121 from '@angular/core/src/error_handler';
import * as import122 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import123 from '@angular/platform-browser/src/dom/animation_driver';
import * as import124 from '@angular/core/src/render/api';
import * as import125 from '@angular/core/src/security';
import * as import126 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import127 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import128 from '@angular/http/src/interfaces';
import * as import129 from '@angular/http/src/http';
import * as import130 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import131 from '@angular/router/src/router_config_loader';
import * as import132 from '@angular/router/src/router_state';
import * as import133 from 'angular2-jwt/angular2-jwt';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ROUTER_FORROOT_GUARD_5:any;
  _RouterModule_6:import7.RouterModule;
  _CompatibilityModule_7:import8.CompatibilityModule;
  _MdRippleModule_8:import9.MdRippleModule;
  _MdOptionModule_9:import10.MdOptionModule;
  _PortalModule_10:import11.PortalModule;
  _OverlayModule_11:import12.OverlayModule;
  _MdAutocompleteModule_12:import13.MdAutocompleteModule;
  _MdButtonModule_13:import14.MdButtonModule;
  _MdCardModule_14:import15.MdCardModule;
  _MdChipsModule_15:import16.MdChipsModule;
  _MdCheckboxModule_16:import17.MdCheckboxModule;
  _MdLineModule_17:import18.MdLineModule;
  _MdGridListModule_18:import19.MdGridListModule;
  _PlatformModule_19:import20.PlatformModule;
  _MdInputModule_20:import21.MdInputModule;
  _MdListModule_21:import22.MdListModule;
  _MdProgressBarModule_22:import23.MdProgressBarModule;
  _MdProgressSpinnerModule_23:import24.MdProgressSpinnerModule;
  _MdSelectModule_24:import25.MdSelectModule;
  _A11yModule_25:import26.A11yModule;
  _MdSidenavModule_26:import27.MdSidenavModule;
  _ObserveContentModule_27:import28.ObserveContentModule;
  _MdTabsModule_28:import29.MdTabsModule;
  _MdToolbarModule_29:import30.MdToolbarModule;
  _ProjectionModule_30:import31.ProjectionModule;
  _RtlModule_31:import32.RtlModule;
  _MdButtonToggleModule_32:import33.MdButtonToggleModule;
  _MdDialogModule_33:import34.MdDialogModule;
  _HttpModule_34:import35.HttpModule;
  _MdIconModule_35:import36.MdIconModule;
  _MdMenuModule_36:import37.MdMenuModule;
  _MdRadioModule_37:import38.MdRadioModule;
  _MdSliderModule_38:import39.MdSliderModule;
  _MdSlideToggleModule_39:import40.MdSlideToggleModule;
  _MdSnackBarModule_40:import41.MdSnackBarModule;
  _MdTooltipModule_41:import42.MdTooltipModule;
  _StyleModule_42:import43.StyleModule;
  _MaterialRootModule_43:import44.MaterialRootModule;
  _AppModule_44:import1.AppModule;
  __LOCALE_ID_45:any;
  __NgLocalization_46:import45.NgLocaleLocalization;
  _ErrorHandler_47:any;
  _ApplicationInitStatus_48:import46.ApplicationInitStatus;
  _Testability_49:import47.Testability;
  _ApplicationRef__50:import48.ApplicationRef_;
  __ApplicationRef_51:any;
  __Compiler_52:import49.Compiler;
  __APP_ID_53:any;
  __DOCUMENT_54:any;
  __HAMMER_GESTURE_CONFIG_55:import50.GestureConfig;
  __EVENT_MANAGER_PLUGINS_56:any[];
  __EventManager_57:import51.EventManager;
  _DomSharedStylesHost_58:import52.DomSharedStylesHost;
  __AnimationDriver_59:any;
  __DomRootRenderer_60:import53.DomRootRenderer_;
  __NgProbeToken_61:any[];
  __RootRenderer_62:any;
  __DomSanitizer_63:import54.DomSanitizerImpl;
  __Sanitizer_64:any;
  __AnimationQueue_65:import55.AnimationQueue;
  __ViewUtils_66:import56.ViewUtils;
  __IterableDiffers_67:any;
  __KeyValueDiffers_68:any;
  __SharedStylesHost_69:any;
  __Title_70:import57.Title;
  __RadioControlRegistry_71:import58.RadioControlRegistry;
  __ScrollDispatcher_72:any;
  __ViewportRuler_73:any;
  __OverlayContainer_74:any;
  __OverlayPositionBuilder_75:import59.OverlayPositionBuilder;
  __Overlay_76:import60.Overlay;
  __Platform_77:import61.Platform;
  __InteractivityChecker_78:import62.InteractivityChecker;
  __LiveAnnouncer_79:any;
  __DomProjection_80:import31.DomProjection;
  __UniqueSelectionDispatcher_81:any;
  __MdDialog_82:import63.MdDialog;
  __BrowserXhr_83:import64.BrowserXhr;
  __ResponseOptions_84:import65.BaseResponseOptions;
  __XSRFStrategy_85:any;
  __XHRBackend_86:import66.XHRBackend;
  __RequestOptions_87:import67.BaseRequestOptions;
  __Http_88:any;
  __MdIconRegistry_89:any;
  __MdSnackBar_90:import68.MdSnackBar;
  __FocusOriginMonitor_91:any;
  __ROUTER_CONFIGURATION_92:any;
  __LocationStrategy_93:any;
  __Location_94:import69.Location;
  __UrlSerializer_95:import70.DefaultUrlSerializer;
  __RouterOutletMap_96:import71.RouterOutletMap;
  __NgModuleFactoryLoader_97:import72.SystemJsNgModuleLoader;
  __ROUTES_98:any[];
  __Router_99:any;
  __ActivatedRoute_100:any;
  _NoPreloading_101:import73.NoPreloading;
  _PreloadingStrategy_102:any;
  _RouterPreloader_103:import73.RouterPreloader;
  __PreloadAllModules_104:import73.PreloadAllModules;
  __ROUTER_INITIALIZER_105:any;
  __APP_BOOTSTRAP_LISTENER_106:any[];
  __AuthHttp_107:any;
  __Server_108:import74.Server;
  __DialogService_109:import75.DialogService;
  __AuthService_110:import76.AuthService;
  __AuthGuard_111:import77.AuthGuard;
  constructor(parent:import78.Injector) {
    super(parent,[
      import79.MdDialogContainerNgFactory,
      import80.MdSnackBarContainerNgFactory,
      import81.SimpleSnackBarNgFactory,
      import82.TooltipComponentNgFactory,
      import83.PatientListComponentNgFactory,
      import84.PatientComponentNgFactory,
      import85.PatientProfileComponentNgFactory,
      import86.FormsListComponentNgFactory,
      import87.FormComponentNgFactory,
      import88.PageNotFoundComponentNgFactory,
      import89.ManageProtocolComponentNgFactory,
      import90.ValidateProtocolComponentNgFactory,
      import91.DialogComponentNgFactory,
      import92.AppComponentNgFactory
    ]
    ,[import92.AppComponentNgFactory]);
  }
  get _LOCALE_ID_45():any {
    if ((this.__LOCALE_ID_45 == null)) { (this.__LOCALE_ID_45 = import3._localeFactory(this.parent.get(import93.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_45;
  }
  get _NgLocalization_46():import45.NgLocaleLocalization {
    if ((this.__NgLocalization_46 == null)) { (this.__NgLocalization_46 = new import45.NgLocaleLocalization(this._LOCALE_ID_45)); }
    return this.__NgLocalization_46;
  }
  get _ApplicationRef_51():any {
    if ((this.__ApplicationRef_51 == null)) { (this.__ApplicationRef_51 = this._ApplicationRef__50); }
    return this.__ApplicationRef_51;
  }
  get _Compiler_52():import49.Compiler {
    if ((this.__Compiler_52 == null)) { (this.__Compiler_52 = new import49.Compiler()); }
    return this.__Compiler_52;
  }
  get _APP_ID_53():any {
    if ((this.__APP_ID_53 == null)) { (this.__APP_ID_53 = import94._appIdRandomProviderFactory()); }
    return this.__APP_ID_53;
  }
  get _DOCUMENT_54():any {
    if ((this.__DOCUMENT_54 == null)) { (this.__DOCUMENT_54 = import4._document()); }
    return this.__DOCUMENT_54;
  }
  get _HAMMER_GESTURE_CONFIG_55():import50.GestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_55 == null)) { (this.__HAMMER_GESTURE_CONFIG_55 = new import50.GestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_55;
  }
  get _EVENT_MANAGER_PLUGINS_56():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_56 == null)) { (this.__EVENT_MANAGER_PLUGINS_56 = [
      new import95.DomEventsPlugin(),
      new import96.KeyEventsPlugin(),
      new import97.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_55)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_56;
  }
  get _EventManager_57():import51.EventManager {
    if ((this.__EventManager_57 == null)) { (this.__EventManager_57 = new import51.EventManager(this._EVENT_MANAGER_PLUGINS_56,this.parent.get(import98.NgZone))); }
    return this.__EventManager_57;
  }
  get _AnimationDriver_59():any {
    if ((this.__AnimationDriver_59 == null)) { (this.__AnimationDriver_59 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_59;
  }
  get _DomRootRenderer_60():import53.DomRootRenderer_ {
    if ((this.__DomRootRenderer_60 == null)) { (this.__DomRootRenderer_60 = new import53.DomRootRenderer_(this._DOCUMENT_54,this._EventManager_57,this._DomSharedStylesHost_58,this._AnimationDriver_59,this._APP_ID_53)); }
    return this.__DomRootRenderer_60;
  }
  get _NgProbeToken_61():any[] {
    if ((this.__NgProbeToken_61 == null)) { (this.__NgProbeToken_61 = [import7.routerNgProbeToken()]); }
    return this.__NgProbeToken_61;
  }
  get _RootRenderer_62():any {
    if ((this.__RootRenderer_62 == null)) { (this.__RootRenderer_62 = import99._createConditionalRootRenderer(this._DomRootRenderer_60,this.parent.get(import99.NgProbeToken,(null as any)),this._NgProbeToken_61)); }
    return this.__RootRenderer_62;
  }
  get _DomSanitizer_63():import54.DomSanitizerImpl {
    if ((this.__DomSanitizer_63 == null)) { (this.__DomSanitizer_63 = new import54.DomSanitizerImpl()); }
    return this.__DomSanitizer_63;
  }
  get _Sanitizer_64():any {
    if ((this.__Sanitizer_64 == null)) { (this.__Sanitizer_64 = this._DomSanitizer_63); }
    return this.__Sanitizer_64;
  }
  get _AnimationQueue_65():import55.AnimationQueue {
    if ((this.__AnimationQueue_65 == null)) { (this.__AnimationQueue_65 = new import55.AnimationQueue(this.parent.get(import98.NgZone))); }
    return this.__AnimationQueue_65;
  }
  get _ViewUtils_66():import56.ViewUtils {
    if ((this.__ViewUtils_66 == null)) { (this.__ViewUtils_66 = new import56.ViewUtils(this._RootRenderer_62,this._Sanitizer_64,this._AnimationQueue_65)); }
    return this.__ViewUtils_66;
  }
  get _IterableDiffers_67():any {
    if ((this.__IterableDiffers_67 == null)) { (this.__IterableDiffers_67 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_67;
  }
  get _KeyValueDiffers_68():any {
    if ((this.__KeyValueDiffers_68 == null)) { (this.__KeyValueDiffers_68 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_68;
  }
  get _SharedStylesHost_69():any {
    if ((this.__SharedStylesHost_69 == null)) { (this.__SharedStylesHost_69 = this._DomSharedStylesHost_58); }
    return this.__SharedStylesHost_69;
  }
  get _Title_70():import57.Title {
    if ((this.__Title_70 == null)) { (this.__Title_70 = new import57.Title()); }
    return this.__Title_70;
  }
  get _RadioControlRegistry_71():import58.RadioControlRegistry {
    if ((this.__RadioControlRegistry_71 == null)) { (this.__RadioControlRegistry_71 = new import58.RadioControlRegistry()); }
    return this.__RadioControlRegistry_71;
  }
  get _ScrollDispatcher_72():any {
    if ((this.__ScrollDispatcher_72 == null)) { (this.__ScrollDispatcher_72 = import100.SCROLL_DISPATCHER_PROVIDER_FACTORY(this.parent.get(import100.ScrollDispatcher,(null as any)))); }
    return this.__ScrollDispatcher_72;
  }
  get _ViewportRuler_73():any {
    if ((this.__ViewportRuler_73 == null)) { (this.__ViewportRuler_73 = import101.VIEWPORT_RULER_PROVIDER_FACTORY(this.parent.get(import101.ViewportRuler,(null as any)),this._ScrollDispatcher_72)); }
    return this.__ViewportRuler_73;
  }
  get _OverlayContainer_74():any {
    if ((this.__OverlayContainer_74 == null)) { (this.__OverlayContainer_74 = import102.OVERLAY_CONTAINER_PROVIDER_FACTORY(this.parent.get(import102.OverlayContainer,(null as any)))); }
    return this.__OverlayContainer_74;
  }
  get _OverlayPositionBuilder_75():import59.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_75 == null)) { (this.__OverlayPositionBuilder_75 = new import59.OverlayPositionBuilder(this._ViewportRuler_73)); }
    return this.__OverlayPositionBuilder_75;
  }
  get _Overlay_76():import60.Overlay {
    if ((this.__Overlay_76 == null)) { (this.__Overlay_76 = new import60.Overlay(this._OverlayContainer_74,this,this._OverlayPositionBuilder_75,this._ApplicationRef_51,this,this.parent.get(import98.NgZone))); }
    return this.__Overlay_76;
  }
  get _Platform_77():import61.Platform {
    if ((this.__Platform_77 == null)) { (this.__Platform_77 = new import61.Platform()); }
    return this.__Platform_77;
  }
  get _InteractivityChecker_78():import62.InteractivityChecker {
    if ((this.__InteractivityChecker_78 == null)) { (this.__InteractivityChecker_78 = new import62.InteractivityChecker(this._Platform_77)); }
    return this.__InteractivityChecker_78;
  }
  get _LiveAnnouncer_79():any {
    if ((this.__LiveAnnouncer_79 == null)) { (this.__LiveAnnouncer_79 = import103.LIVE_ANNOUNCER_PROVIDER_FACTORY(this.parent.get(import103.LiveAnnouncer,(null as any)),this.parent.get(import103.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__LiveAnnouncer_79;
  }
  get _DomProjection_80():import31.DomProjection {
    if ((this.__DomProjection_80 == null)) { (this.__DomProjection_80 = new import31.DomProjection()); }
    return this.__DomProjection_80;
  }
  get _UniqueSelectionDispatcher_81():any {
    if ((this.__UniqueSelectionDispatcher_81 == null)) { (this.__UniqueSelectionDispatcher_81 = import104.UNIQUE_SELECTION_DISPATCHER_PROVIDER_FACTORY(this.parent.get(import104.UniqueSelectionDispatcher,(null as any)))); }
    return this.__UniqueSelectionDispatcher_81;
  }
  get _MdDialog_82():import63.MdDialog {
    if ((this.__MdDialog_82 == null)) { (this.__MdDialog_82 = new import63.MdDialog(this._Overlay_76,this,this.parent.get(import63.MdDialog,(null as any)))); }
    return this.__MdDialog_82;
  }
  get _BrowserXhr_83():import64.BrowserXhr {
    if ((this.__BrowserXhr_83 == null)) { (this.__BrowserXhr_83 = new import64.BrowserXhr()); }
    return this.__BrowserXhr_83;
  }
  get _ResponseOptions_84():import65.BaseResponseOptions {
    if ((this.__ResponseOptions_84 == null)) { (this.__ResponseOptions_84 = new import65.BaseResponseOptions()); }
    return this.__ResponseOptions_84;
  }
  get _XSRFStrategy_85():any {
    if ((this.__XSRFStrategy_85 == null)) { (this.__XSRFStrategy_85 = import35._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_85;
  }
  get _XHRBackend_86():import66.XHRBackend {
    if ((this.__XHRBackend_86 == null)) { (this.__XHRBackend_86 = new import66.XHRBackend(this._BrowserXhr_83,this._ResponseOptions_84,this._XSRFStrategy_85)); }
    return this.__XHRBackend_86;
  }
  get _RequestOptions_87():import67.BaseRequestOptions {
    if ((this.__RequestOptions_87 == null)) { (this.__RequestOptions_87 = new import67.BaseRequestOptions()); }
    return this.__RequestOptions_87;
  }
  get _Http_88():any {
    if ((this.__Http_88 == null)) { (this.__Http_88 = import35.httpFactory(this._XHRBackend_86,this._RequestOptions_87)); }
    return this.__Http_88;
  }
  get _MdIconRegistry_89():any {
    if ((this.__MdIconRegistry_89 == null)) { (this.__MdIconRegistry_89 = import36.ICON_REGISTRY_PROVIDER_FACTORY(this.parent.get(import105.MdIconRegistry,(null as any)),this._Http_88,this._DomSanitizer_63)); }
    return this.__MdIconRegistry_89;
  }
  get _MdSnackBar_90():import68.MdSnackBar {
    if ((this.__MdSnackBar_90 == null)) { (this.__MdSnackBar_90 = new import68.MdSnackBar(this._Overlay_76,this._LiveAnnouncer_79,this.parent.get(import68.MdSnackBar,(null as any)))); }
    return this.__MdSnackBar_90;
  }
  get _FocusOriginMonitor_91():any {
    if ((this.__FocusOriginMonitor_91 == null)) { (this.__FocusOriginMonitor_91 = import106.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY(this.parent.get(import106.FocusOriginMonitor,(null as any)))); }
    return this.__FocusOriginMonitor_91;
  }
  get _ROUTER_CONFIGURATION_92():any {
    if ((this.__ROUTER_CONFIGURATION_92 == null)) { (this.__ROUTER_CONFIGURATION_92 = {}); }
    return this.__ROUTER_CONFIGURATION_92;
  }
  get _LocationStrategy_93():any {
    if ((this.__LocationStrategy_93 == null)) { (this.__LocationStrategy_93 = import7.provideLocationStrategy(this.parent.get(import107.PlatformLocation),this.parent.get(import108.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_92)); }
    return this.__LocationStrategy_93;
  }
  get _Location_94():import69.Location {
    if ((this.__Location_94 == null)) { (this.__Location_94 = new import69.Location(this._LocationStrategy_93)); }
    return this.__Location_94;
  }
  get _UrlSerializer_95():import70.DefaultUrlSerializer {
    if ((this.__UrlSerializer_95 == null)) { (this.__UrlSerializer_95 = new import70.DefaultUrlSerializer()); }
    return this.__UrlSerializer_95;
  }
  get _RouterOutletMap_96():import71.RouterOutletMap {
    if ((this.__RouterOutletMap_96 == null)) { (this.__RouterOutletMap_96 = new import71.RouterOutletMap()); }
    return this.__RouterOutletMap_96;
  }
  get _NgModuleFactoryLoader_97():import72.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_97 == null)) { (this.__NgModuleFactoryLoader_97 = new import72.SystemJsNgModuleLoader(this._Compiler_52,this.parent.get(import72.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_97;
  }
  get _ROUTES_98():any[] {
      if ((this.__ROUTES_98 == null)) { (this.__ROUTES_98 = [[
        {
          path: '',
          pathMatch: 'full',
          redirectTo: '/patient-list'
        }
        ,
        {
          path: 'patient-list',
          component: import109.PatientListComponent
        }
        ,
        {
          path: 'patient',
          component: import110.PatientComponent,
          children: [
            {
              path: '',
              pathMatch: 'full',
              redirectTo: '0/profile'
            }
            ,
            {
              path: ':id',
              pathMatch: 'full',
              redirectTo: ':id/profile'
            }
            ,
            {
              path: ':id/profile',
              component: import111.PatientProfileComponent
            }
            ,
            {
              path: ':id/forms-list',
              component: import112.FormsListComponent
            }
            ,
            {
              path: ':id/form/:type',
              component: import113.FormComponent
            }
            ,
            {
              path: '**',
              component: import114.PageNotFoundComponent
            }

          ]
          ,
          canActivate: [import77.AuthGuard]
        }
        ,
        {
          path: 'manage-protocol',
          component: import115.ManageProtocolComponent
        }
        ,
        {
          path: 'validate-protocol',
          component: import116.ValidateProtocolComponent
        }
        ,
        {
          path: '**',
          component: import114.PageNotFoundComponent
        }

      ]
    ]); }
    return this.__ROUTES_98;
  }
  get _Router_99():any {
    if ((this.__Router_99 == null)) { (this.__Router_99 = import7.setupRouter(this._ApplicationRef_51,this._UrlSerializer_95,this._RouterOutletMap_96,this._Location_94,this,this._NgModuleFactoryLoader_97,this._Compiler_52,this._ROUTES_98,this._ROUTER_CONFIGURATION_92,this.parent.get(import117.UrlHandlingStrategy,(null as any)),this.parent.get(import118.RouteReuseStrategy,(null as any)))); }
    return this.__Router_99;
  }
  get _ActivatedRoute_100():any {
    if ((this.__ActivatedRoute_100 == null)) { (this.__ActivatedRoute_100 = import7.rootRoute(this._Router_99)); }
    return this.__ActivatedRoute_100;
  }
  get _PreloadAllModules_104():import73.PreloadAllModules {
    if ((this.__PreloadAllModules_104 == null)) { (this.__PreloadAllModules_104 = new import73.PreloadAllModules()); }
    return this.__PreloadAllModules_104;
  }
  get _ROUTER_INITIALIZER_105():any {
    if ((this.__ROUTER_INITIALIZER_105 == null)) { (this.__ROUTER_INITIALIZER_105 = import7.initialRouterNavigation(this._Router_99,this._ApplicationRef_51,this._RouterPreloader_103,this._ROUTER_CONFIGURATION_92)); }
    return this.__ROUTER_INITIALIZER_105;
  }
  get _APP_BOOTSTRAP_LISTENER_106():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_106 == null)) { (this.__APP_BOOTSTRAP_LISTENER_106 = [this._ROUTER_INITIALIZER_105]); }
    return this.__APP_BOOTSTRAP_LISTENER_106;
  }
  get _AuthHttp_107():any {
    if ((this.__AuthHttp_107 == null)) { (this.__AuthHttp_107 = import1.authHttpServiceFactory(this._Http_88,this._RequestOptions_87)); }
    return this.__AuthHttp_107;
  }
  get _Server_108():import74.Server {
    if ((this.__Server_108 == null)) { (this.__Server_108 = new import74.Server(this._Http_88,this._AuthHttp_107)); }
    return this.__Server_108;
  }
  get _DialogService_109():import75.DialogService {
    if ((this.__DialogService_109 == null)) { (this.__DialogService_109 = new import75.DialogService(this._MdDialog_82)); }
    return this.__DialogService_109;
  }
  get _AuthService_110():import76.AuthService {
    if ((this.__AuthService_110 == null)) { (this.__AuthService_110 = new import76.AuthService(this._Router_99)); }
    return this.__AuthService_110;
  }
  get _AuthGuard_111():import77.AuthGuard {
    if ((this.__AuthGuard_111 == null)) { (this.__AuthGuard_111 = new import77.AuthGuard(this._AuthService_110,this._Router_99)); }
    return this.__AuthGuard_111;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ROUTER_FORROOT_GUARD_5 = import7.provideForRootGuard(this.parent.get(import119.Router,(null as any)));
    this._RouterModule_6 = new import7.RouterModule(this._ROUTER_FORROOT_GUARD_5);
    this._CompatibilityModule_7 = new import8.CompatibilityModule();
    this._MdRippleModule_8 = new import9.MdRippleModule();
    this._MdOptionModule_9 = new import10.MdOptionModule();
    this._PortalModule_10 = new import11.PortalModule();
    this._OverlayModule_11 = new import12.OverlayModule();
    this._MdAutocompleteModule_12 = new import13.MdAutocompleteModule();
    this._MdButtonModule_13 = new import14.MdButtonModule();
    this._MdCardModule_14 = new import15.MdCardModule();
    this._MdChipsModule_15 = new import16.MdChipsModule();
    this._MdCheckboxModule_16 = new import17.MdCheckboxModule();
    this._MdLineModule_17 = new import18.MdLineModule();
    this._MdGridListModule_18 = new import19.MdGridListModule();
    this._PlatformModule_19 = new import20.PlatformModule();
    this._MdInputModule_20 = new import21.MdInputModule();
    this._MdListModule_21 = new import22.MdListModule();
    this._MdProgressBarModule_22 = new import23.MdProgressBarModule();
    this._MdProgressSpinnerModule_23 = new import24.MdProgressSpinnerModule();
    this._MdSelectModule_24 = new import25.MdSelectModule();
    this._A11yModule_25 = new import26.A11yModule();
    this._MdSidenavModule_26 = new import27.MdSidenavModule();
    this._ObserveContentModule_27 = new import28.ObserveContentModule();
    this._MdTabsModule_28 = new import29.MdTabsModule();
    this._MdToolbarModule_29 = new import30.MdToolbarModule();
    this._ProjectionModule_30 = new import31.ProjectionModule();
    this._RtlModule_31 = new import32.RtlModule();
    this._MdButtonToggleModule_32 = new import33.MdButtonToggleModule();
    this._MdDialogModule_33 = new import34.MdDialogModule();
    this._HttpModule_34 = new import35.HttpModule();
    this._MdIconModule_35 = new import36.MdIconModule();
    this._MdMenuModule_36 = new import37.MdMenuModule();
    this._MdRadioModule_37 = new import38.MdRadioModule();
    this._MdSliderModule_38 = new import39.MdSliderModule();
    this._MdSlideToggleModule_39 = new import40.MdSlideToggleModule();
    this._MdSnackBarModule_40 = new import41.MdSnackBarModule();
    this._MdTooltipModule_41 = new import42.MdTooltipModule();
    this._StyleModule_42 = new import43.StyleModule();
    this._MaterialRootModule_43 = new import44.MaterialRootModule();
    this._AppModule_44 = new import1.AppModule();
    this._ErrorHandler_47 = import4.errorHandler();
    this._ApplicationInitStatus_48 = new import46.ApplicationInitStatus(this.parent.get(import46.APP_INITIALIZER,(null as any)));
    this._Testability_49 = new import47.Testability(this.parent.get(import98.NgZone));
    this._ApplicationRef__50 = new import48.ApplicationRef_(this.parent.get(import98.NgZone),this.parent.get(import120.Console),this,this._ErrorHandler_47,this,this._ApplicationInitStatus_48,this.parent.get(import47.TestabilityRegistry,(null as any)),this._Testability_49);
    this._DomSharedStylesHost_58 = new import52.DomSharedStylesHost(this._DOCUMENT_54);
    this._NoPreloading_101 = new import73.NoPreloading();
    this._PreloadingStrategy_102 = this._NoPreloading_101;
    this._RouterPreloader_103 = new import73.RouterPreloader(this._Router_99,this._NgModuleFactoryLoader_97,this._Compiler_52,this,this._PreloadingStrategy_102);
    return this._AppModule_44;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_5; }
    if ((token === import7.RouterModule)) { return this._RouterModule_6; }
    if ((token === import8.CompatibilityModule)) { return this._CompatibilityModule_7; }
    if ((token === import9.MdRippleModule)) { return this._MdRippleModule_8; }
    if ((token === import10.MdOptionModule)) { return this._MdOptionModule_9; }
    if ((token === import11.PortalModule)) { return this._PortalModule_10; }
    if ((token === import12.OverlayModule)) { return this._OverlayModule_11; }
    if ((token === import13.MdAutocompleteModule)) { return this._MdAutocompleteModule_12; }
    if ((token === import14.MdButtonModule)) { return this._MdButtonModule_13; }
    if ((token === import15.MdCardModule)) { return this._MdCardModule_14; }
    if ((token === import16.MdChipsModule)) { return this._MdChipsModule_15; }
    if ((token === import17.MdCheckboxModule)) { return this._MdCheckboxModule_16; }
    if ((token === import18.MdLineModule)) { return this._MdLineModule_17; }
    if ((token === import19.MdGridListModule)) { return this._MdGridListModule_18; }
    if ((token === import20.PlatformModule)) { return this._PlatformModule_19; }
    if ((token === import21.MdInputModule)) { return this._MdInputModule_20; }
    if ((token === import22.MdListModule)) { return this._MdListModule_21; }
    if ((token === import23.MdProgressBarModule)) { return this._MdProgressBarModule_22; }
    if ((token === import24.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_23; }
    if ((token === import25.MdSelectModule)) { return this._MdSelectModule_24; }
    if ((token === import26.A11yModule)) { return this._A11yModule_25; }
    if ((token === import27.MdSidenavModule)) { return this._MdSidenavModule_26; }
    if ((token === import28.ObserveContentModule)) { return this._ObserveContentModule_27; }
    if ((token === import29.MdTabsModule)) { return this._MdTabsModule_28; }
    if ((token === import30.MdToolbarModule)) { return this._MdToolbarModule_29; }
    if ((token === import31.ProjectionModule)) { return this._ProjectionModule_30; }
    if ((token === import32.RtlModule)) { return this._RtlModule_31; }
    if ((token === import33.MdButtonToggleModule)) { return this._MdButtonToggleModule_32; }
    if ((token === import34.MdDialogModule)) { return this._MdDialogModule_33; }
    if ((token === import35.HttpModule)) { return this._HttpModule_34; }
    if ((token === import36.MdIconModule)) { return this._MdIconModule_35; }
    if ((token === import37.MdMenuModule)) { return this._MdMenuModule_36; }
    if ((token === import38.MdRadioModule)) { return this._MdRadioModule_37; }
    if ((token === import39.MdSliderModule)) { return this._MdSliderModule_38; }
    if ((token === import40.MdSlideToggleModule)) { return this._MdSlideToggleModule_39; }
    if ((token === import41.MdSnackBarModule)) { return this._MdSnackBarModule_40; }
    if ((token === import42.MdTooltipModule)) { return this._MdTooltipModule_41; }
    if ((token === import43.StyleModule)) { return this._StyleModule_42; }
    if ((token === import44.MaterialRootModule)) { return this._MaterialRootModule_43; }
    if ((token === import1.AppModule)) { return this._AppModule_44; }
    if ((token === import93.LOCALE_ID)) { return this._LOCALE_ID_45; }
    if ((token === import45.NgLocalization)) { return this._NgLocalization_46; }
    if ((token === import121.ErrorHandler)) { return this._ErrorHandler_47; }
    if ((token === import46.ApplicationInitStatus)) { return this._ApplicationInitStatus_48; }
    if ((token === import47.Testability)) { return this._Testability_49; }
    if ((token === import48.ApplicationRef_)) { return this._ApplicationRef__50; }
    if ((token === import48.ApplicationRef)) { return this._ApplicationRef_51; }
    if ((token === import49.Compiler)) { return this._Compiler_52; }
    if ((token === import94.APP_ID)) { return this._APP_ID_53; }
    if ((token === import122.DOCUMENT)) { return this._DOCUMENT_54; }
    if ((token === import97.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_55; }
    if ((token === import51.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_56; }
    if ((token === import51.EventManager)) { return this._EventManager_57; }
    if ((token === import52.DomSharedStylesHost)) { return this._DomSharedStylesHost_58; }
    if ((token === import123.AnimationDriver)) { return this._AnimationDriver_59; }
    if ((token === import53.DomRootRenderer)) { return this._DomRootRenderer_60; }
    if ((token === import48.NgProbeToken)) { return this._NgProbeToken_61; }
    if ((token === import124.RootRenderer)) { return this._RootRenderer_62; }
    if ((token === import54.DomSanitizer)) { return this._DomSanitizer_63; }
    if ((token === import125.Sanitizer)) { return this._Sanitizer_64; }
    if ((token === import55.AnimationQueue)) { return this._AnimationQueue_65; }
    if ((token === import56.ViewUtils)) { return this._ViewUtils_66; }
    if ((token === import126.IterableDiffers)) { return this._IterableDiffers_67; }
    if ((token === import127.KeyValueDiffers)) { return this._KeyValueDiffers_68; }
    if ((token === import52.SharedStylesHost)) { return this._SharedStylesHost_69; }
    if ((token === import57.Title)) { return this._Title_70; }
    if ((token === import58.RadioControlRegistry)) { return this._RadioControlRegistry_71; }
    if ((token === import100.ScrollDispatcher)) { return this._ScrollDispatcher_72; }
    if ((token === import101.ViewportRuler)) { return this._ViewportRuler_73; }
    if ((token === import102.OverlayContainer)) { return this._OverlayContainer_74; }
    if ((token === import59.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_75; }
    if ((token === import60.Overlay)) { return this._Overlay_76; }
    if ((token === import61.Platform)) { return this._Platform_77; }
    if ((token === import62.InteractivityChecker)) { return this._InteractivityChecker_78; }
    if ((token === import103.LiveAnnouncer)) { return this._LiveAnnouncer_79; }
    if ((token === import31.DomProjection)) { return this._DomProjection_80; }
    if ((token === import104.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_81; }
    if ((token === import63.MdDialog)) { return this._MdDialog_82; }
    if ((token === import64.BrowserXhr)) { return this._BrowserXhr_83; }
    if ((token === import65.ResponseOptions)) { return this._ResponseOptions_84; }
    if ((token === import128.XSRFStrategy)) { return this._XSRFStrategy_85; }
    if ((token === import66.XHRBackend)) { return this._XHRBackend_86; }
    if ((token === import67.RequestOptions)) { return this._RequestOptions_87; }
    if ((token === import129.Http)) { return this._Http_88; }
    if ((token === import105.MdIconRegistry)) { return this._MdIconRegistry_89; }
    if ((token === import68.MdSnackBar)) { return this._MdSnackBar_90; }
    if ((token === import106.FocusOriginMonitor)) { return this._FocusOriginMonitor_91; }
    if ((token === import7.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_92; }
    if ((token === import108.LocationStrategy)) { return this._LocationStrategy_93; }
    if ((token === import69.Location)) { return this._Location_94; }
    if ((token === import70.UrlSerializer)) { return this._UrlSerializer_95; }
    if ((token === import71.RouterOutletMap)) { return this._RouterOutletMap_96; }
    if ((token === import130.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_97; }
    if ((token === import131.ROUTES)) { return this._ROUTES_98; }
    if ((token === import119.Router)) { return this._Router_99; }
    if ((token === import132.ActivatedRoute)) { return this._ActivatedRoute_100; }
    if ((token === import73.NoPreloading)) { return this._NoPreloading_101; }
    if ((token === import73.PreloadingStrategy)) { return this._PreloadingStrategy_102; }
    if ((token === import73.RouterPreloader)) { return this._RouterPreloader_103; }
    if ((token === import73.PreloadAllModules)) { return this._PreloadAllModules_104; }
    if ((token === import7.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_105; }
    if ((token === import94.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_106; }
    if ((token === import133.AuthHttp)) { return this._AuthHttp_107; }
    if ((token === import74.Server)) { return this._Server_108; }
    if ((token === import75.DialogService)) { return this._DialogService_109; }
    if ((token === import76.AuthService)) { return this._AuthService_110; }
    if ((token === import77.AuthGuard)) { return this._AuthGuard_111; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__50.ngOnDestroy();
    this._DomSharedStylesHost_58.ngOnDestroy();
    this._RouterPreloader_103.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);