/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../src/app/patient-list.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../src/app/server.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from './patient-list.component.css.shim.ngstyle';
import * as import11 from '@angular/material/card/card';
import * as import12 from '../../node_modules/@angular/material/core/compatibility/compatibility.ngfactory';
import * as import13 from '../../node_modules/@angular/material/card/card.ngfactory';
import * as import14 from '@angular/material/menu/menu-directive';
import * as import15 from '../../node_modules/@angular/material/menu/menu-directive.ngfactory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '@angular/material/menu/menu-item';
import * as import18 from '../../node_modules/@angular/material/menu/menu-item.ngfactory';
import * as import19 from '@angular/core/src/linker/view_container';
import * as import20 from '../../node_modules/@angular/material/menu/menu-trigger.ngfactory';
import * as import21 from '@angular/core/src/change_detection/change_detection_util';
import * as import22 from '@angular/material/core/compatibility/compatibility';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from '@angular/material/core/overlay/overlay';
import * as import25 from '@angular/material/core/rtl/dir';
import * as import26 from '@angular/material/menu/menu-trigger';
import * as import27 from '@angular/material/button/button';
import * as import28 from '../../node_modules/@angular/material/button/button.ngfactory';
import * as import29 from '@angular/material/toolbar/toolbar';
import * as import30 from '../../node_modules/@angular/material/toolbar/toolbar.ngfactory';
import * as import31 from '@angular/material/input/input-container';
import * as import32 from '../../node_modules/@angular/material/input/input-container.ngfactory';
import * as import33 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import34 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import35 from '@angular/forms/src/directives/ng_control';
import * as import36 from '@angular/core/src/linker/template_ref';
import * as import37 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import38 from '@angular/common/src/directives/ng_for';
import * as import39 from '@angular/common/src/directives/ng_if';
export class Wrapper_PatientListComponent {
  /*private*/ _eventHandler:Function;
  context:import0.PatientListComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.PatientListComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_PatientListComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_PatientListComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.PatientListComponent>;
  _PatientListComponent_0_3:Wrapper_PatientListComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PatientListComponent_Host0,renderType_PatientListComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'patient-list',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_PatientListComponent0(this.viewUtils,this,0,this._el_0);
    this._PatientListComponent_0_3 = new Wrapper_PatientListComponent(this.injectorGet(import8.Server,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex));
    this.compView_0.create(this._PatientListComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._PatientListComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PatientListComponent) && (0 === requestNodeIndex))) { return this._PatientListComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PatientListComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PatientListComponentNgFactory:import7.ComponentFactory<import0.PatientListComponent> = new import7.ComponentFactory<import0.PatientListComponent>('patient-list',View_PatientListComponent_Host0,import0.PatientListComponent);
const styles_PatientListComponent:any[] = [import10.styles];
class View_PatientListComponent1 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import11.MdCard>;
  _MdPrefixRejector_0_3:import12.Wrapper_MdPrefixRejector;
  _MdCard_0_4:import13.Wrapper_MdCard;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import14.MdMenu>;
  _MdPrefixRejector_2_3:import12.Wrapper_MdPrefixRejector;
  _MdMenu_2_4:import15.Wrapper_MdMenu;
  _query_MdMenuItem_2_0:import16.QueryList<any>;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import17.MdMenuItem>;
  _MdMenuItem_4_3:import18.Wrapper_MdMenuItem;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  compView_7:import1.AppView<import17.MdMenuItem>;
  _MdMenuItem_7_3:import18.Wrapper_MdMenuItem;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _MdPrefixRejector_11_3:import12.Wrapper_MdPrefixRejector;
  _MdCardTitle_11_4:import13.Wrapper_MdCardTitle;
  _text_12:any;
  _el_13:any;
  /*private*/ _vc_13:import19.ViewContainer;
  _MdMenuTrigger_13_5:import20.Wrapper_MdMenuTrigger;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_PatientListComponent1,renderType_PatientListComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_51 = import21.UNINITIALIZED;
    this._expr_52 = import21.UNINITIALIZED;
    this._expr_53 = import21.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'md-card',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import13.View_MdCard0(this.viewUtils,this,0,this._el_0);
    this._MdPrefixRejector_0_3 = new import12.Wrapper_MdPrefixRejector(this.parentView.parentView.injectorGet(import22.MATERIAL_COMPATIBILITY_MODE,this.parentView.parentIndex,(null as any)));
    this._MdCard_0_4 = new import13.Wrapper_MdCard();
    this._text_1 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'md-menu',new import3.InlineArray2(2,'role','menu'),(null as any));
    this.compView_2 = new import15.View_MdMenu0(this.viewUtils,this,2,this._el_2);
    this._MdPrefixRejector_2_3 = new import12.Wrapper_MdPrefixRejector(this.parentView.parentView.injectorGet(import22.MATERIAL_COMPATIBILITY_MODE,this.parentView.parentIndex,(null as any)));
    this._MdMenu_2_4 = new import15.Wrapper_MdMenu((null as any),(null as any));
    this._query_MdMenuItem_2_0 = new import16.QueryList<any>();
    this._text_3 = this.renderer.createText((null as any),'\n		  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'md-menu-item','','role','menuitem'),(null as any));
    this.compView_4 = new import18.View_MdMenuItem0(this.viewUtils,this,4,this._el_4);
    this._MdMenuItem_4_3 = new import18.Wrapper_MdMenuItem(this.renderer,new import23.ElementRef(this._el_4));
    this._text_5 = this.renderer.createText((null as any),'Insulin infusion',(null as any));
    this.compView_4.create(this._MdMenuItem_4_3.context);
    this._text_6 = this.renderer.createText((null as any),'\n		  ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'md-menu-item','','role','menuitem'),(null as any));
    this.compView_7 = new import18.View_MdMenuItem0(this.viewUtils,this,7,this._el_7);
    this._MdMenuItem_7_3 = new import18.Wrapper_MdMenuItem(this.renderer,new import23.ElementRef(this._el_7));
    this._text_8 = this.renderer.createText((null as any),'Subcutaneous insulin',(null as any));
    this.compView_7.create(this._MdMenuItem_7_3.context);
    this._text_9 = this.renderer.createText((null as any),'\n		',(null as any));
    this.compView_2.create(this._MdMenu_2_4.context);
    this._text_10 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,(null as any),'md-card-title',new import3.InlineArray2(2,'style','cursor:pointer;'),(null as any));
    this._MdPrefixRejector_11_3 = new import12.Wrapper_MdPrefixRejector(this.parentView.parentView.injectorGet(import22.MATERIAL_COMPATIBILITY_MODE,this.parentView.parentIndex,(null as any)));
    this._MdCardTitle_11_4 = new import13.Wrapper_MdCardTitle();
    this._text_12 = this.renderer.createText(this._el_11,'\n			',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'span',new import3.InlineArray2(2,'aria-haspopup','true'),(null as any));
    this._vc_13 = new import19.ViewContainer(13,11,this,this._el_13);
    this._MdMenuTrigger_13_5 = new import20.Wrapper_MdMenuTrigger(this.parentView.parentView.injectorGet(import24.Overlay,this.parentView.parentIndex),new import23.ElementRef(this._el_13),this._vc_13.vcRef,this.renderer,this.parentView.parentView.injectorGet(import25.Dir,this.parentView.parentIndex,(null as any)));
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n			',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_11,'i',new import3.InlineArray2(2,'class','material-icons fright'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'list',(null as any));
    this._text_18 = this.renderer.createText(this._el_11,'\n			',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_11,'i',new import3.InlineArray2(2,'class','material-icons fright'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'mode_edit',(null as any));
    this._text_21 = this.renderer.createText(this._el_11,'\n		',(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n		\n		',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n			',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'div',new import3.InlineArray2(2,'class','fright halfwidth'),(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_25,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Bed Number: ',(null as any));
    this._text_28 = this.renderer.createText(this._el_25,'',(null as any));
    this._text_29 = this.renderer.createText(this._el_23,'\n			',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_23,'div',new import3.InlineArray2(2,'class','halfwidth'),(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_30,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'UHID: ',(null as any));
    this._text_33 = this.renderer.createText(this._el_30,'',(null as any));
    this._text_34 = this.renderer.createText(this._el_23,'		\n		',(null as any));
    this._text_35 = this.renderer.createText((null as any),'\n	',(null as any));
    this.compView_0.create(this._MdCard_0_4.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_4));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_7));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_13,new import3.InlineArray4(4,'mousedown',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_13));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_16,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_16));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_19,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_19));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.MdMenuItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._MdMenuItem_4_3.context; }
    if (((token === import17.MdMenuItem) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._MdMenuItem_7_3.context; }
    if (((token === import22.MdPrefixRejector) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._MdPrefixRejector_2_3.context; }
    if (((token === import14.MdMenu) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._MdMenu_2_4.context; }
    if (((token === import26.MdMenuTrigger) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._MdMenuTrigger_13_5.context; }
    if (((token === import22.MdPrefixRejector) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdPrefixRejector_11_3.context; }
    if (((token === import11.MdCardTitle) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdCardTitle_11_4.context; }
    if (((token === import22.MdPrefixRejector) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._MdPrefixRejector_0_3.context; }
    if (((token === import11.MdCard) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._MdCard_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MdPrefixRejector_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    if (this._MdCard_0_4.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._MdPrefixRejector_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._MdMenu_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    this._MdMenuItem_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this._MdMenuItem_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this._MdPrefixRejector_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    this._MdCardTitle_11_4.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_13_0_0:any = this._MdMenu_2_4.context;
    this._MdMenuTrigger_13_5.check_menu(currVal_13_0_0,throwOnChange,false);
    this._MdMenuTrigger_13_5.ngDoCheck(this,this._el_13,throwOnChange);
    this._vc_13.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdMenuItem_2_0.dirty) {
        this._query_MdMenuItem_2_0.reset([
          this._MdMenuItem_4_3.context,
          this._MdMenuItem_7_3.context
        ]
        );
        this._MdMenu_2_4.context.items = this._query_MdMenuItem_2_0;
        this._query_MdMenuItem_2_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdMenu_2_4.context.ngAfterContentInit(); }
    }
    this._MdCard_0_4.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    this._MdMenuItem_4_3.checkHost(this,this.compView_4,this._el_4,throwOnChange);
    this._MdMenuItem_7_3.checkHost(this,this.compView_7,this._el_7,throwOnChange);
    this._MdCardTitle_11_4.checkHost(this,this,this._el_11,throwOnChange);
    const currVal_51:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setText(this._text_14,currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = import3.inlineInterpolate(1,'',this.context.$implicit.bednum,'');
    if (import3.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setText(this._text_28,currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:any = import3.inlineInterpolate(1,' ',this.context.$implicit.uhid,'');
    if (import3.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setText(this._text_33,currVal_53);
      this._expr_53 = currVal_53;
    }
    this.compView_0.internalDetectChanges(throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_4.internalDetectChanges(throwOnChange);
    this.compView_7.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._MdMenuTrigger_13_5.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._vc_13.destroyNestedViews();
    this.compView_0.destroy();
    this.compView_2.destroy();
    this.compView_4.destroy();
    this.compView_7.destroy();
    this._MdMenu_2_4.ngOnDestroy();
    this._MdMenuTrigger_13_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_10,ctx);
      cb(this._el_11,ctx);
      cb(this._text_22,ctx);
      cb(this._el_23,ctx);
      cb(this._text_35,ctx);
    }
    if (((nodeIndex == 2) && (ngContentIndex == 0))) {
      cb(this._text_3,ctx);
      cb(this._el_4,ctx);
      cb(this._text_6,ctx);
      cb(this._el_7,ctx);
      cb(this._text_9,ctx);
    }
    if (((nodeIndex == 4) && (ngContentIndex == 0))) { cb(this._text_5,ctx); }
    if (((nodeIndex == 7) && (ngContentIndex == 0))) { cb(this._text_8,ctx); }
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.compView_4.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdMenuItem_4_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.showForm(this.context.$implicit.id,'infusion')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.compView_7.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdMenuItem_7_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.showForm(this.context.$implicit.id,'subcutaneous')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_13(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdMenuTrigger_13_5.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.formsList(this.context.$implicit.id)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_19(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.editPatient(this.context.$implicit.id)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_PatientListComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  compView_10:import1.AppView<import27.MdButton>;
  _MdPrefixRejector_10_3:import12.Wrapper_MdPrefixRejector;
  _MdButton_10_4:import28.Wrapper_MdButton;
  _MdRaisedButtonCssMatStyler_10_5:import28.Wrapper_MdRaisedButtonCssMatStyler;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_PatientListComponent2,renderType_PatientListComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'style','text-align:center;'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'style','margin:2em auto;'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n			No patient found',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_2,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'Add a new patient to proceed	\n		',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'	\n		',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'style','margin:1em auto;'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n			',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray2(2,'md-raised-button',''),(null as any));
    this.compView_10 = new import28.View_MdButton0(this.viewUtils,this,10,this._el_10);
    this._MdPrefixRejector_10_3 = new import12.Wrapper_MdPrefixRejector(this.parentView.parentView.injectorGet(import22.MATERIAL_COMPATIBILITY_MODE,this.parentView.parentIndex,(null as any)));
    this._MdButton_10_4 = new import28.Wrapper_MdButton(new import23.ElementRef(this._el_10),this.renderer);
    this._MdRaisedButtonCssMatStyler_10_5 = new import28.Wrapper_MdRaisedButtonCssMatStyler();
    this._text_11 = this.renderer.createText((null as any),'Add a patient',(null as any));
    this.compView_10.create(this._MdButton_10_4.context);
    this._text_12 = this.renderer.createText(this._el_8,'	\n		',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'	\n	',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_10));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.MdPrefixRejector) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdPrefixRejector_10_3.context; }
    if (((token === import27.MdButton) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdButton_10_4.context; }
    if (((token === import27.MdRaisedButtonCssMatStyler) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdRaisedButtonCssMatStyler_10_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MdPrefixRejector_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    if (this._MdButton_10_4.ngDoCheck(this,this._el_10,throwOnChange)) { this.compView_10.markAsCheckOnce(); }
    this._MdRaisedButtonCssMatStyler_10_5.ngDoCheck(this,this._el_10,throwOnChange);
    this._MdButton_10_4.checkHost(this,this.compView_10,this._el_10,throwOnChange);
    this._MdRaisedButtonCssMatStyler_10_5.checkHost(this,this.compView_10,this._el_10,throwOnChange);
    this.compView_10.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_10.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 10) && (ngContentIndex == 0))) { cb(this._text_11,ctx); }
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.compView_10.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_10_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.newPatient((<View_PatientListComponent0>this.parentView)._el_20.value)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_PatientListComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_PatientListComponent,{});
export class View_PatientListComponent0 extends import1.AppView<import0.PatientListComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import29.MdToolbar>;
  _MdPrefixRejector_2_3:import12.Wrapper_MdPrefixRejector;
  _MdToolbar_2_4:import30.Wrapper_MdToolbar;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  compView_18:import1.AppView<import31.MdInputContainer>;
  _MdInputContainer_18_3:import32.Wrapper_MdInputContainer;
  _query_MdInputDirective_18_0:import16.QueryList<any>;
  _query_MdPlaceholder_18_1:import16.QueryList<any>;
  _query_MdHint_18_2:import16.QueryList<any>;
  _text_19:any;
  _el_20:any;
  _MdInputDirective_20_3:import32.Wrapper_MdInputDirective;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _vc_27:import19.ViewContainer;
  _TemplateRef_27_5:any;
  _NgFor_27_6:import33.Wrapper_NgFor;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _vc_29:import19.ViewContainer;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import34.Wrapper_NgIf;
  _text_30:any;
  _text_31:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PatientListComponent0,renderType_PatientListComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','topfixed'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'md-toolbar',new import3.InlineArray4(4,'color','primary','role','toolbar'),(null as any));
    this.compView_2 = new import30.View_MdToolbar0(this.viewUtils,this,2,this._el_2);
    this._MdPrefixRejector_2_3 = new import12.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import22.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdToolbar_2_4 = new import30.Wrapper_MdToolbar(new import23.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Glucose control advisor',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray2(2,'class','filler'),(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray2(2,'class','material-icons'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'assignment',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray2(2,'class','material-icons'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'account_circle',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n	',(null as any));
    this.compView_2.create(this._MdToolbar_2_4.context);
    this._text_15 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'style','padding:5px;'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n		',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'md-input-container',new import3.InlineArray2(2,'style','width:100%;'),(null as any));
    this.compView_18 = new import32.View_MdInputContainer0(this.viewUtils,this,18,this._el_18);
    this._MdInputContainer_18_3 = new import32.Wrapper_MdInputContainer();
    this._query_MdInputDirective_18_0 = new import16.QueryList<any>();
    this._query_MdPlaceholder_18_1 = new import16.QueryList<any>();
    this._query_MdHint_18_2 = new import16.QueryList<any>();
    this._text_19 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray8(8,'mdInput','','name','search','placeholder','Search by UHID','type','search'),(null as any));
    this._MdInputDirective_20_3 = new import32.Wrapper_MdInputDirective(new import23.ElementRef(this._el_20),this.renderer,this.parentView.injectorGet(import35.NgControl,this.parentIndex,(null as any)));
    this._text_21 = this.renderer.createText((null as any),'\n		',(null as any));
    this.compView_18.create(this._MdInputContainer_18_3.context);
    this._text_22 = this.renderer.createText(this._el_16,'\n	',(null as any));
    this._text_23 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_24 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'style','padding:120px 5px 0 5px;box-sizing:border-box;overflow:scroll;height:100%;'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'	\n	',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._vc_27 = new import19.ViewContainer(27,25,this,this._anchor_27);
    this._TemplateRef_27_5 = new import36.TemplateRef_(this,27,this._anchor_27);
    this._NgFor_27_6 = new import33.Wrapper_NgFor(this._vc_27.vcRef,this._TemplateRef_27_5,this.parentView.injectorGet(import37.IterableDiffers,this.parentIndex),this.ref);
    this._text_28 = this.renderer.createText(this._el_25,'\n	',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._vc_29 = new import19.ViewContainer(29,25,this,this._anchor_29);
    this._TemplateRef_29_5 = new import36.TemplateRef_(this,29,this._anchor_29);
    this._NgIf_29_6 = new import34.Wrapper_NgIf(this._vc_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText(this._el_25,'\n	\n',(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_18));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray8(8,'keyup',(null as any),'blur',(null as any),'focus',(null as any),'input',(null as any)),this.eventHandler(this.handleEvent_20));
    this._query_MdInputDirective_18_0.reset([this._MdInputDirective_20_3.context]);
    this._MdInputContainer_18_3.context._mdInputChild = this._query_MdInputDirective_18_0.first;
    this._query_MdPlaceholder_18_1.reset(([] as any[]));
    this._MdInputContainer_18_3.context._placeholderChild = this._query_MdPlaceholder_18_1.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._text_31
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.MdPrefixRejector) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._MdPrefixRejector_2_3.context; }
    if (((token === import29.MdToolbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._MdToolbar_2_4.context; }
    if (((token === import31.MdInputDirective) && (20 === requestNodeIndex))) { return this._MdInputDirective_20_3.context; }
    if (((token === import31.MdInputContainer) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdInputContainer_18_3.context; }
    if (((token === import36.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import38.NgFor) && (27 === requestNodeIndex))) { return this._NgFor_27_6.context; }
    if (((token === import36.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import39.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MdPrefixRejector_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_1_0:any = 'primary';
    this._MdToolbar_2_4.check_color(currVal_2_1_0,throwOnChange,false);
    if (this._MdToolbar_2_4.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    this._MdInputContainer_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_20_0_0:any = 'Search by UHID';
    this._MdInputDirective_20_3.check_placeholder(currVal_20_0_0,throwOnChange,false);
    const currVal_20_0_1:any = 'search';
    this._MdInputDirective_20_3.check_type(currVal_20_0_1,throwOnChange,false);
    this._MdInputDirective_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_27_0_0:any = this.context.patients;
    this._NgFor_27_6.check_ngForOf(currVal_27_0_0,throwOnChange,false);
    this._NgFor_27_6.ngDoCheck(this,this._anchor_27,throwOnChange);
    const currVal_29_0_0:boolean = (!this.context.patients || !this.context.patients.length);
    this._NgIf_29_6.check_ngIf(currVal_29_0_0,throwOnChange,false);
    this._NgIf_29_6.ngDoCheck(this,this._anchor_29,throwOnChange);
    this._vc_27.detectChangesInNestedViews(throwOnChange);
    this._vc_29.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_18_2.dirty) {
        this._query_MdHint_18_2.reset(([] as any[]));
        this._MdInputContainer_18_3.context._hintChildren = this._query_MdHint_18_2;
        this._query_MdHint_18_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdInputContainer_18_3.context.ngAfterContentInit(); }
    }
    this._MdToolbar_2_4.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this._MdInputContainer_18_3.checkHost(this,this.compView_18,this._el_18,throwOnChange);
    this._MdInputDirective_20_3.checkHost(this,this,this._el_20,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_18.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_27.destroyNestedViews();
    this._vc_29.destroyNestedViews();
    this.compView_2.destroy();
    this.compView_18.destroy();
    this._MdInputDirective_20_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) {
      cb(this._text_3,ctx);
      cb(this._el_4,ctx);
      cb(this._text_6,ctx);
      cb(this._el_7,ctx);
      cb(this._text_8,ctx);
      cb(this._el_9,ctx);
      cb(this._text_11,ctx);
      cb(this._el_12,ctx);
      cb(this._text_14,ctx);
    }
    if (((nodeIndex == 2) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 1))) {
      cb(this._text_19,ctx);
      cb(this._el_20,ctx);
      cb(this._text_21,ctx);
    }
    if (((nodeIndex == 18) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 4))) {  }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 27)) { return new View_PatientListComponent1(this.viewUtils,this,27,this._anchor_27,this._vc_27); }
    if ((nodeIndex == 29)) { return new View_PatientListComponent2(this.viewUtils,this,29,this._anchor_29,this._vc_29); }
    return (null as any);
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.compView_18.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInputContainer_18_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInputDirective_20_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'keyup')) {
      const pd_sub_0:any = ((<any>(($event.keyCode == 13) && this.context.onSearch(this._el_20.value))) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}