/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../src/app/patient-list.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../src/app/server.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../../src/app/auth.service';
import * as import11 from './patient-list.component.css.shim.ngstyle';
import * as import12 from '@angular/material/card/card';
import * as import13 from '../../node_modules/@angular/material/core/compatibility/compatibility.ngfactory';
import * as import14 from '../../node_modules/@angular/material/card/card.ngfactory';
import * as import15 from '@angular/core/src/linker/view_container';
import * as import16 from '@angular/core/src/change_detection/change_detection_util';
import * as import17 from '@angular/material/core/compatibility/compatibility';
import * as import18 from '@angular/material/button/button';
import * as import19 from '../../node_modules/@angular/material/button/button.ngfactory';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/material/toolbar/toolbar';
import * as import22 from '../../node_modules/@angular/material/toolbar/toolbar.ngfactory';
import * as import23 from '@angular/material/input/input-container';
import * as import24 from '../../node_modules/@angular/material/input/input-container.ngfactory';
import * as import25 from '@angular/core/src/linker/query_list';
import * as import26 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import27 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import28 from '@angular/forms/src/directives/ng_control';
import * as import29 from '@angular/core/src/linker/template_ref';
import * as import30 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import31 from '@angular/common/src/directives/ng_for';
import * as import32 from '@angular/common/src/directives/ng_if';
export class Wrapper_PatientListComponent {
  /*private*/ _eventHandler:Function;
  context:import0.PatientListComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.PatientListComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_PatientListComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_PatientListComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.PatientListComponent>;
  _PatientListComponent_0_3:Wrapper_PatientListComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PatientListComponent_Host0,renderType_PatientListComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'patient-list',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_PatientListComponent0(this.viewUtils,this,0,this._el_0);
    this._PatientListComponent_0_3 = new Wrapper_PatientListComponent(this.injectorGet(import8.Server,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injectorGet(import10.AuthService,this.parentIndex));
    this.compView_0.create(this._PatientListComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._PatientListComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PatientListComponent) && (0 === requestNodeIndex))) { return this._PatientListComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PatientListComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PatientListComponentNgFactory:import7.ComponentFactory<import0.PatientListComponent> = new import7.ComponentFactory<import0.PatientListComponent>('patient-list',View_PatientListComponent_Host0,import0.PatientListComponent);
const styles_PatientListComponent:any[] = [import11.styles];
class View_PatientListComponent1 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import12.MdCard>;
  _MdPrefixRejector_0_3:import13.Wrapper_MdPrefixRejector;
  _MdCard_0_4:import14.Wrapper_MdCard;
  _text_1:any;
  _el_2:any;
  _MdPrefixRejector_2_3:import13.Wrapper_MdPrefixRejector;
  _MdCardTitle_2_4:import14.Wrapper_MdCardTitle;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_PatientListComponent1,renderType_PatientListComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_32 = import16.UNINITIALIZED;
    this._expr_33 = import16.UNINITIALIZED;
    this._expr_34 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'md-card',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import14.View_MdCard0(this.viewUtils,this,0,this._el_0);
    this._MdPrefixRejector_0_3 = new import13.Wrapper_MdPrefixRejector(this.parentView.parentView.injectorGet(import17.MATERIAL_COMPATIBILITY_MODE,this.parentView.parentIndex,(null as any)));
    this._MdCard_0_4 = new import14.Wrapper_MdCard();
    this._text_1 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'md-card-title',new import3.InlineArray2(2,'style','cursor:pointer;'),(null as any));
    this._MdPrefixRejector_2_3 = new import13.Wrapper_MdPrefixRejector(this.parentView.parentView.injectorGet(import17.MATERIAL_COMPATIBILITY_MODE,this.parentView.parentIndex,(null as any)));
    this._MdCardTitle_2_4 = new import14.Wrapper_MdCardTitle();
    this._text_3 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'i',new import3.InlineArray2(2,'class','material-icons fright'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'list',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_2,'i',new import3.InlineArray2(2,'class','material-icons fright'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'mode_edit',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n		\n		',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n			',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'div',new import3.InlineArray2(2,'class','fright halfwidth'),(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_16,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Bed Number: ',(null as any));
    this._text_19 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_20 = this.renderer.createText(this._el_14,'\n			',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_14,'div',new import3.InlineArray2(2,'class','halfwidth'),(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_21,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'UHID: ',(null as any));
    this._text_24 = this.renderer.createText(this._el_21,'',(null as any));
    this._text_25 = this.renderer.createText(this._el_14,'		\n		',(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n	',(null as any));
    this.compView_0.create(this._MdCard_0_4.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_4));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_7));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_10));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.MdPrefixRejector) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._MdPrefixRejector_2_3.context; }
    if (((token === import12.MdCardTitle) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._MdCardTitle_2_4.context; }
    if (((token === import17.MdPrefixRejector) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._MdPrefixRejector_0_3.context; }
    if (((token === import12.MdCard) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._MdCard_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MdPrefixRejector_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    if (this._MdCard_0_4.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._MdPrefixRejector_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._MdCardTitle_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    this._MdCard_0_4.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    this._MdCardTitle_2_4.checkHost(this,this,this._el_2,throwOnChange);
    const currVal_32:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setText(this._text_5,currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = import3.inlineInterpolate(1,'',this.context.$implicit.bednum,'');
    if (import3.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setText(this._text_19,currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = import3.inlineInterpolate(1,' ',this.context.$implicit.uhid,'');
    if (import3.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setText(this._text_24,currVal_34);
      this._expr_34 = currVal_34;
    }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_13,ctx);
      cb(this._el_14,ctx);
      cb(this._text_26,ctx);
    }
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.showForm(this.context.$implicit.id)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.formsList(this.context.$implicit.id)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.editPatient(this.context.$implicit.id)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_PatientListComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  compView_10:import1.AppView<import18.MdButton>;
  _MdPrefixRejector_10_3:import13.Wrapper_MdPrefixRejector;
  _MdButton_10_4:import19.Wrapper_MdButton;
  _MdRaisedButtonCssMatStyler_10_5:import19.Wrapper_MdRaisedButtonCssMatStyler;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_PatientListComponent2,renderType_PatientListComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'style','text-align:center;'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'style','margin:2em auto;'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n			No patient found',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_2,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'Add a new patient to proceed	\n		',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'	\n		',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'style','margin:1em auto;'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n			',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray2(2,'md-raised-button',''),(null as any));
    this.compView_10 = new import19.View_MdButton0(this.viewUtils,this,10,this._el_10);
    this._MdPrefixRejector_10_3 = new import13.Wrapper_MdPrefixRejector(this.parentView.parentView.injectorGet(import17.MATERIAL_COMPATIBILITY_MODE,this.parentView.parentIndex,(null as any)));
    this._MdButton_10_4 = new import19.Wrapper_MdButton(new import20.ElementRef(this._el_10),this.renderer);
    this._MdRaisedButtonCssMatStyler_10_5 = new import19.Wrapper_MdRaisedButtonCssMatStyler();
    this._text_11 = this.renderer.createText((null as any),'Add a patient',(null as any));
    this.compView_10.create(this._MdButton_10_4.context);
    this._text_12 = this.renderer.createText(this._el_8,'	\n		',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'	\n	',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_10));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.MdPrefixRejector) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdPrefixRejector_10_3.context; }
    if (((token === import18.MdButton) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdButton_10_4.context; }
    if (((token === import18.MdRaisedButtonCssMatStyler) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdRaisedButtonCssMatStyler_10_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MdPrefixRejector_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    if (this._MdButton_10_4.ngDoCheck(this,this._el_10,throwOnChange)) { this.compView_10.markAsCheckOnce(); }
    this._MdRaisedButtonCssMatStyler_10_5.ngDoCheck(this,this._el_10,throwOnChange);
    this._MdButton_10_4.checkHost(this,this.compView_10,this._el_10,throwOnChange);
    this._MdRaisedButtonCssMatStyler_10_5.checkHost(this,this.compView_10,this._el_10,throwOnChange);
    this.compView_10.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_10.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 10) && (ngContentIndex == 0))) { cb(this._text_11,ctx); }
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.compView_10.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_10_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.newPatient((<View_PatientListComponent0>this.parentView)._el_20.value)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_PatientListComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_PatientListComponent,{});
export class View_PatientListComponent0 extends import1.AppView<import0.PatientListComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import21.MdToolbar>;
  _MdPrefixRejector_2_3:import13.Wrapper_MdPrefixRejector;
  _MdToolbar_2_4:import22.Wrapper_MdToolbar;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  compView_18:import1.AppView<import23.MdInputContainer>;
  _MdInputContainer_18_3:import24.Wrapper_MdInputContainer;
  _query_MdInputDirective_18_0:import25.QueryList<any>;
  _query_MdPlaceholder_18_1:import25.QueryList<any>;
  _query_MdHint_18_2:import25.QueryList<any>;
  _text_19:any;
  _el_20:any;
  _MdInputDirective_20_3:import24.Wrapper_MdInputDirective;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _vc_27:import15.ViewContainer;
  _TemplateRef_27_5:any;
  _NgFor_27_6:import26.Wrapper_NgFor;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _vc_29:import15.ViewContainer;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import27.Wrapper_NgIf;
  _text_30:any;
  _text_31:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PatientListComponent0,renderType_PatientListComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','topfixed'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'md-toolbar',new import3.InlineArray4(4,'color','primary','role','toolbar'),(null as any));
    this.compView_2 = new import22.View_MdToolbar0(this.viewUtils,this,2,this._el_2);
    this._MdPrefixRejector_2_3 = new import13.Wrapper_MdPrefixRejector(this.parentView.injectorGet(import17.MATERIAL_COMPATIBILITY_MODE,this.parentIndex,(null as any)));
    this._MdToolbar_2_4 = new import22.Wrapper_MdToolbar(new import20.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Glucose control advisor',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray2(2,'class','filler'),(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray2(2,'class','material-icons'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'assignment',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray2(2,'class','material-icons'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'account_circle',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n	',(null as any));
    this.compView_2.create(this._MdToolbar_2_4.context);
    this._text_15 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'style','padding:5px;'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n		',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'md-input-container',new import3.InlineArray2(2,'style','width:100%;'),(null as any));
    this.compView_18 = new import24.View_MdInputContainer0(this.viewUtils,this,18,this._el_18);
    this._MdInputContainer_18_3 = new import24.Wrapper_MdInputContainer();
    this._query_MdInputDirective_18_0 = new import25.QueryList<any>();
    this._query_MdPlaceholder_18_1 = new import25.QueryList<any>();
    this._query_MdHint_18_2 = new import25.QueryList<any>();
    this._text_19 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray8(8,'mdInput','','name','search','placeholder','Search by UHID','type','search'),(null as any));
    this._MdInputDirective_20_3 = new import24.Wrapper_MdInputDirective(new import20.ElementRef(this._el_20),this.renderer,this.parentView.injectorGet(import28.NgControl,this.parentIndex,(null as any)));
    this._text_21 = this.renderer.createText((null as any),'\n		',(null as any));
    this.compView_18.create(this._MdInputContainer_18_3.context);
    this._text_22 = this.renderer.createText(this._el_16,'\n	',(null as any));
    this._text_23 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_24 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'style','padding:120px 5px 0 5px;box-sizing:border-box;overflow:scroll;height:100%;'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'	\n	',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._vc_27 = new import15.ViewContainer(27,25,this,this._anchor_27);
    this._TemplateRef_27_5 = new import29.TemplateRef_(this,27,this._anchor_27);
    this._NgFor_27_6 = new import26.Wrapper_NgFor(this._vc_27.vcRef,this._TemplateRef_27_5,this.parentView.injectorGet(import30.IterableDiffers,this.parentIndex),this.ref);
    this._text_28 = this.renderer.createText(this._el_25,'\n	',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._vc_29 = new import15.ViewContainer(29,25,this,this._anchor_29);
    this._TemplateRef_29_5 = new import29.TemplateRef_(this,29,this._anchor_29);
    this._NgIf_29_6 = new import27.Wrapper_NgIf(this._vc_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText(this._el_25,'\n	\n',(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_18));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray8(8,'keyup',(null as any),'blur',(null as any),'focus',(null as any),'input',(null as any)),this.eventHandler(this.handleEvent_20));
    this._query_MdInputDirective_18_0.reset([this._MdInputDirective_20_3.context]);
    this._MdInputContainer_18_3.context._mdInputChild = this._query_MdInputDirective_18_0.first;
    this._query_MdPlaceholder_18_1.reset(([] as any[]));
    this._MdInputContainer_18_3.context._placeholderChild = this._query_MdPlaceholder_18_1.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._text_31
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.MdPrefixRejector) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._MdPrefixRejector_2_3.context; }
    if (((token === import21.MdToolbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._MdToolbar_2_4.context; }
    if (((token === import23.MdInputDirective) && (20 === requestNodeIndex))) { return this._MdInputDirective_20_3.context; }
    if (((token === import23.MdInputContainer) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdInputContainer_18_3.context; }
    if (((token === import29.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import31.NgFor) && (27 === requestNodeIndex))) { return this._NgFor_27_6.context; }
    if (((token === import29.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import32.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MdPrefixRejector_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_1_0:any = 'primary';
    this._MdToolbar_2_4.check_color(currVal_2_1_0,throwOnChange,false);
    if (this._MdToolbar_2_4.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    this._MdInputContainer_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_20_0_0:any = 'Search by UHID';
    this._MdInputDirective_20_3.check_placeholder(currVal_20_0_0,throwOnChange,false);
    const currVal_20_0_1:any = 'search';
    this._MdInputDirective_20_3.check_type(currVal_20_0_1,throwOnChange,false);
    this._MdInputDirective_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_27_0_0:any = this.context.patients;
    this._NgFor_27_6.check_ngForOf(currVal_27_0_0,throwOnChange,false);
    this._NgFor_27_6.ngDoCheck(this,this._anchor_27,throwOnChange);
    const currVal_29_0_0:boolean = (!this.context.patients || !this.context.patients.length);
    this._NgIf_29_6.check_ngIf(currVal_29_0_0,throwOnChange,false);
    this._NgIf_29_6.ngDoCheck(this,this._anchor_29,throwOnChange);
    this._vc_27.detectChangesInNestedViews(throwOnChange);
    this._vc_29.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_18_2.dirty) {
        this._query_MdHint_18_2.reset(([] as any[]));
        this._MdInputContainer_18_3.context._hintChildren = this._query_MdHint_18_2;
        this._query_MdHint_18_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdInputContainer_18_3.context.ngAfterContentInit(); }
    }
    this._MdToolbar_2_4.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this._MdInputContainer_18_3.checkHost(this,this.compView_18,this._el_18,throwOnChange);
    this._MdInputDirective_20_3.checkHost(this,this,this._el_20,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_18.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_27.destroyNestedViews();
    this._vc_29.destroyNestedViews();
    this.compView_2.destroy();
    this.compView_18.destroy();
    this._MdInputDirective_20_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) {
      cb(this._text_3,ctx);
      cb(this._el_4,ctx);
      cb(this._text_6,ctx);
      cb(this._el_7,ctx);
      cb(this._text_8,ctx);
      cb(this._el_9,ctx);
      cb(this._text_11,ctx);
      cb(this._el_12,ctx);
      cb(this._text_14,ctx);
    }
    if (((nodeIndex == 2) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 1))) {
      cb(this._text_19,ctx);
      cb(this._el_20,ctx);
      cb(this._text_21,ctx);
    }
    if (((nodeIndex == 18) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 4))) {  }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 27)) { return new View_PatientListComponent1(this.viewUtils,this,27,this._anchor_27,this._vc_27); }
    if ((nodeIndex == 29)) { return new View_PatientListComponent2(this.viewUtils,this,29,this._anchor_29,this._vc_29); }
    return (null as any);
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.compView_18.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInputContainer_18_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInputDirective_20_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'keyup')) {
      const pd_sub_0:any = ((<any>(($event.keyCode == 13) && this.context.onSearch(this._el_20.value))) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}